Use mktemp to avoid following symlinks, fix permissions
Use mktemp to avoid following symlinks that might allow the user
running 'modem update-prl' to write arbitrary files.  Also ensure that
the permissions on the file created in the temporary directory are set
such that all users can read the file.

BUG=chromium-os:17020
TEST=cp /usr/share/prl/madison.prl ~ ; chmod 600 ~/madison.prl ; modem update-prl ~/madison.prl ; ls -l /tmp/prl*

Change-Id: I59cadbe04c022f5c81012d709c36050667dcdc17
Reviewed-on: http://gerrit.chromium.org/gerrit/3310
Reviewed-by: Eric Shienbrood <ers@chromium.org>
Tested-by: Jason Glasgow <jglasgow@chromium.org>

diff --git a/modem-utilities/modem b/modem-utilities/modem
--- a/modem-utilities/modem
+++ b/modem-utilities/modem
@@ -196,20 +196,21 @@ update_prl () {
 	# the script does. A specific example is the Downloads folder,
 	# which only the "chronos" user has access to. To work
 	# around this problem, we copy the PRL file to /tmp.
-	if ! echo "$prlfile" | grep -q '^/tmp/'; then
-		prlbase=${prlfile##*/}
-		cp $prlfile /tmp/$prlbase
-		if [ $? -ne 0 ]; then
-			echo "Cannot copy PRL file \"$prlfile\" to temp directory"
-			exit 1
-		fi
-		prlfile=/tmp/$prlbase
+	local tmpfile=$(mktemp --tmpdir prl.XXXXXXXXXX)
+	trap "rm -f $tmpfile" 1 2 13 15
+	cp $prlfile $tmpfile
+	if [ $? -ne 0 ]; then
+		echo "Cannot copy \"$prlfile\" to \"$tmpfile\" directory"
+		rm -f $tmpfile
+		exit 1
 	fi
+	chmod 644 $tmpfile
 	local oldstate=$(modem_activation_state $modem)
-        args="mdn,$mdn,min,$min,prlfile,$prlfile"
+	args="mdn,$mdn,min,$min,prlfile,$tmpfile"
 	dbus "$modem" $IMODEM_CDMA.ActivateManualDebug \
 	  "dict:string:string:$args"
-        wait_for_modem_reset $modem 40
+	wait_for_modem_reset $modem 40
+	rm -f $tmpfile
 }
 
 usage () {
