powerd - Detect failed writes to /sys/power/state
If a driver fails to suspend, the error code is returned from the
write call to /sys/power/state. Use this to detect if suspend fails,
and send that status along with the PowerStateChanged dbus message.

If suspend fails, powerman shouldn't reset the retry count.

BUG=chromium-os:33675
TEST=modified tpm driver to always fail suspend; try suspend
Change-Id: I25796648328b86356b9412f244d0b91dfc9b3ab1
Reviewed-on: https://gerrit.chromium.org/gerrit/30910
Reviewed-by: Jon Kliegman <kliegs@chromium.org>
Commit-Ready: Michael Spang <spang@chromium.org>
Tested-by: Michael Spang <spang@chromium.org>

diff --git a/power_manager/powerd_suspend b/power_manager/powerd_suspend
--- a/power_manager/powerd_suspend
+++ b/power_manager/powerd_suspend
@@ -90,7 +90,7 @@ cp /sys/class/rtc/rtc0/since_epoch /var/log/metrics/suspend-to-ram-time \
 
 # - announces the event
 /usr/bin/dbus-send --type=signal --system /org/chromium/PowerManager \
-  org.chromium.PowerManager.PowerStateChanged string:mem
+  org.chromium.PowerManager.PowerStateChanged string:mem int32:0
 
 # - stores the current power status
 power_status_on_suspend=/var/log/metrics/power-status-on-suspend
@@ -123,6 +123,7 @@ rm -f /var/run/power_manager/hwclock-on-resume
 log_msg "Explicit sync"
 sync
 
+suspend_rc=-1
 if suspend_cancel; then
     log_msg "Cancel suspend at kernel"
 else
@@ -134,6 +135,11 @@ else
     fi
     # - suspends to ram
     echo -n mem > /sys/power/state
+    suspend_rc=$?
+    if [ "${suspend_rc}" != 0 ]; then
+        log_msg "Error writing to /sys/power/state"
+        log_msg -f /sys/kernel/debug/suspend_stats
+    fi
 fi
 
 if [ $cancel -eq 0 ]; then
@@ -165,7 +171,8 @@ fi
 
 # - announces the event
 /usr/bin/dbus-send --type=signal --system /org/chromium/PowerManager \
-    org.chromium.PowerManager.PowerStateChanged string:on &
+    org.chromium.PowerManager.PowerStateChanged string:on \
+    "int32:${suspend_rc}" &
 
 cleanup_for_resume
 
