dded distinction between DEV_MODE and CROS_DEBUG
Developer mode is represented by the variable DEV_MODE in this script.
CROS_DEBUG is a pseudo-boolean variable that equals to DEV_MODE || DEV_IMAGE.
CROS_DEBUG is 1 if we are in developer mode or we've booted a developer image.
CROS_DEBUG is used to determine if we need to mount /usr/local. DEV_MODE is
used to determine if we need to go through the transition to/from developer
mode and normal mode.

BUG=chromium-os:16648
TEST=Run cros_au_test_harness. Also boot a base image in developer mode and
check for a correct mount of /usr/local. After that, check that the transition
to normal mode goes as expected.

Change-Id: Iee5c89d929f1850d7d4e1a4ff5f21adda800025e
Reviewed-on: http://gerrit.chromium.org/gerrit/4177
Reviewed-by: Arkaitz Ruiz Alvarez <arkaitzr@chromium.org>
Tested-by: Arkaitz Ruiz Alvarez <arkaitzr@chromium.org>

diff --git a/init/chromeos_startup b/init/chromeos_startup
--- a/init/chromeos_startup
+++ b/init/chromeos_startup
@@ -81,11 +81,16 @@ if [ "$ROOTDEV_RET_CODE" = "0" -a "$ROOTDEV_TYPE" != "/dev/ram" ]; then
   fi
 fi
 
-# DEVMODE is used to determine if we're booted in developer mode,
+# DEV_MODE is used to determine if we're booted in developer mode,
 # by checking only the developer and recovery switch states.
 # Values: 0=recovery/non-dev mode, 1=dev (SSD) mode, 2=bypass devcheck
 crossystem devsw_boot?1 recoverysw_boot?0
-DEVMODE=$((! $?))
+DEV_MODE=$((! $?))
+
+# CROS_DEBUG equals one if we've booted in developer mode or we've booted a
+# developer image.
+crossystem cros_debug?1
+CROS_DEBUG=$((! $?))
 
 # Check if we need to perform firmware update.
 FIRMWARE_UPDATE_SCRIPT=/usr/sbin/chromeos-firmwareupdate
@@ -102,7 +107,9 @@ if [ -x "$FIRMWARE_UPDATE_SCRIPT" ]; then
       tries=$((tries - 1))
       crossystem fwupdate_tries=$tries
 
-      if [ "$DEVMODE" = "1" -o -f /root/.dev_mode ]; then
+      # TODO(arkaitzr): remove references to /root/.dev_mode in this file if
+      # CROS_DEBUG is also being check since CROS_DEBUG==1 for dev images.
+      if [ "$CROS_DEBUG" = "1" -o -f /root/.dev_mode ]; then
         # More message on console for developer mode and dev builds
         FIRMWARE_UPDATE_LOGS="/dev/tty1 $FIRMWARE_UPDATE_LOGS"
       fi
@@ -127,14 +134,14 @@ fi
 RESET_FILE="/mnt/stateful_partition/factory_install_reset"
 
 # File defined by clobber-state
-DEVMODE_FILE="/mnt/stateful_partition/.developer_mode"
+DEV_MODE_FILE="/mnt/stateful_partition/.developer_mode"
 
 # If in factory mode or a wipe process is already scheduled, don't change it.
 if [ -n "$IS_FACTORY_MODE" -o -O "$RESET_FILE" ]; then
-  DEVMODE=2
+  DEV_MODE=2
 fi
 
-if [ ${DEVMODE} -eq 1 ]; then
+if [ ${DEV_MODE} -eq 1 ]; then
   PLATFORM=$(mosys platform name)
   FW_TYPE=$(crossystem mainfw_type)
   # Mario always displays the developer mode warning in firmware while
@@ -146,7 +153,7 @@ if [ ${DEVMODE} -eq 1 ]; then
 fi
 
 # Transition to devmode
-if [ ${DEVMODE} -eq 1 -a ! -O ${DEVMODE_FILE} ]; then
+if [ ${DEV_MODE} -eq 1 -a ! -O ${DEV_MODE_FILE} ]; then
   # Delay the first developer mode boot by 5 minutes unless the images is a
   # developer image.  We check the dev image here to avoid a stat(2) on normal
   # boots
@@ -161,7 +168,7 @@ if [ ${DEVMODE} -eq 1 -a ! -O ${DEVMODE_FILE} ]; then
   fi
 
   # Transition from devmode
-elif [ ${DEVMODE} -eq 0 -a -O ${DEVMODE_FILE} ]; then
+elif [ ${DEV_MODE} -eq 0 -a -O ${DEV_MODE_FILE} ]; then
   # When coming back from developer mode, we don't need to clobber
   # as aggressively. Fast will do the trick.
   if [ ! -f /root/.dev_mode ]; then
@@ -246,8 +253,14 @@ mount -n --bind /mnt/stateful_partition/home /home
 #mod_for_test#mount -n -o remount,exec,suid /tmp
 
 # Mount stateful partition for dev packages
-# TODO(sosa@chromium.org) - Use $DEVMODE value?
-if [ -f /root/.dev_mode ] ; then
+# TODO(arkaitzr@chromium.org) - Only use CROS_DEBUG when cros_debug is
+# correctly set in a test VM after updating itself to itself (that is, it does
+# not fail cros_au_test_harness).
+if [ "$CROS_DEBUG" = "1" -o -f /root/.dev_mode ]; then
+  # Create dev_image directory in base images in developer mode.
+  if [ ! -d /mnt/stateful_partition/dev_image ]; then
+    mkdir -p -m 0755 /mnt/stateful_partition/dev_image
+  fi
   # Mount and then remount to enable exec/suid
   mount -n --bind /mnt/stateful_partition/dev_image /usr/local
   mount -n -o remount,exec,suid /usr/local
