init: print devfw checking messages only for v2 updaters
In firmware updater v3+, we don't need printing firmware information anymore
because developer mode will still get firmware updated.

The startup time firmware updating procedure is also refined to get better
performance. Before this CL, booting an Alex in normal mode requires 4 command
calls to check if firmware updating is required: ( [ -x file ],
crossytem mainfw_type, mosys platform, and crossystem fwupdate_tries ); and
this CL simplied that to one command (crossystem mainfw_type? fwupdate_tries?).

BUG=chrome-os-partner:4510
TEST=(alex) boot system in normal mode (see nothing);
            install old firmware and turn on developer mode firmware
            (chromeos-firmware --mode=todev), then reboot; seeing devfw message.
     (non-alex/zgb) boot system in normal mode (see nothing);
            install old firmware and turn on developer mode firmware
            (chromeos-firmware --mode=todev), then reboot; seeing nothing.

Change-Id: I27750bd22f8d670703863754bdab09bf9adf2536
Reviewed-on: http://gerrit.chromium.org/gerrit/8267
Reviewed-by: Richard Barnette <jrbarnette@chromium.org>
Reviewed-by: Randall Spangler <rspangler@chromium.org>
Tested-by: Hung-Te Lin <hungte@chromium.org>

diff --git a/init/chromeos_startup b/init/chromeos_startup
--- a/init/chromeos_startup
+++ b/init/chromeos_startup
@@ -92,36 +92,41 @@ DEV_MODE=$((! $?))
 crossystem cros_debug?1
 CROS_DEBUG=$((! $?))
 
-# Check if we need to perform firmware update.
+# Check if we need to perform firmware update: only if fwupdate_tries is
+# non-zero or if not using normal (ex, developer or recovery) firmware.
 FIRMWARE_UPDATE_SCRIPT=/usr/sbin/chromeos-firmwareupdate
-if [ -x "$FIRMWARE_UPDATE_SCRIPT" ]; then
+if ! crossystem "fwupdate_tries?0" "mainfw_type?normal" &&
+   [ -x "$FIRMWARE_UPDATE_SCRIPT" ]; then
   # This file will be collected by chromeos-setgoodkernel
   FIRMWARE_UPDATE_LOGS=/mnt/stateful_partition/update_firmware.log
+  tries="$(crossystem fwupdate_tries || echo 0)"
 
-  if [ "$(crossystem mainfw_type)" = developer ]; then
-    # TODO(hungte) Only alert for v2 firmware.
-    chromeos-boot-alert dev_fwcheck /dev/tty1
-  elif [ "$(mosys platform name 2>/dev/null)" = "Mario" ]; then
-    # Prevent any unexpected updates on legacy system
-    crossystem fwupdate_tries=0 >/dev/null 2>&1
-  else
-    tries="$(crossystem fwupdate_tries || echo 0)"
-    if [ $tries -gt 0 ]; then
-      tries=$((tries - 1))
-      crossystem fwupdate_tries=$tries
-
-      if [ "$CROS_DEBUG" = "1" ]; then
-        # More message on console for developer mode and dev builds
-        FIRMWARE_UPDATE_LOGS="/dev/tty1 $FIRMWARE_UPDATE_LOGS"
+  # Special updating rules for legacy systems.
+  case "$(mosys platform name 2>/dev/null)" in
+    Mario )
+      tries=0  # Prevents any unexpected updates on CR48.
+      ;;
+    Alex | ZGB )
+      if [ "$(crossystem mainfw_type)" = developer ]; then
+        tries=0  # Prevents updates if we're in developer mode
+        [ -z "$BOOT_SPLASH_PID" ] || wait $BOOT_SPLASH_PID
+        chromeos-boot-alert dev_fwcheck /dev/tty1
       fi
-      [ -z "$BOOT_SPLASH_PID" ] || wait $BOOT_SPLASH_PID
-      chromeos-boot-alert update_firmware /dev/tty1
-      (date && "$FIRMWARE_UPDATE_SCRIPT" --mode=startup 2>&1) |
-        tee -a $FIRMWARE_UPDATE_LOGS
-      # Send ANSI "clear screen" escape sequence to clear TTY frame buffer, to
-      # prevent user seeing the messages again in shutdown
-      printf '\033[2J' >/dev/tty1
-    fi
+      ;;
+  esac
+
+  if [ $tries -gt 0 ]; then
+    crossystem fwupdate_tries=$((tries - 1))
+    # More messages on console for developer mode and dev builds.
+    [ "$CROS_DEBUG" = "1" ] &&
+      FIRMWARE_UPDATE_LOGS="/dev/tty1 $FIRMWARE_UPDATE_LOGS" || true
+    [ -z "$BOOT_SPLASH_PID" ] || wait $BOOT_SPLASH_PID
+    chromeos-boot-alert update_firmware /dev/tty1
+    (date && "$FIRMWARE_UPDATE_SCRIPT" --mode=startup 2>&1) |
+      tee -a $FIRMWARE_UPDATE_LOGS
+    # Sends "clear screen" terminal command to clear TTY frame buffer, to
+    # prevent user seeing the messages again on system shutdown.
+    [ "$CROS_DEBUG" = 1 ] && tput clear >/dev/tty1 || true
   fi
 fi
 
