init: Nuke symlinks in /var/log on boot
This clears out symlinks within /var/log that point elsewhere on the
file system. In general, symlinks in /var/log are only allowed for
convenience (i.e. .CURRENT, .PREVIOUS for log files), but there's no
legit reason to have symlinks pointing to elsewhere on the file
system (the VPD file is an exception, but that symlink gets recreated
by the vpd init job).

BUG=chromium:916152
TEST=Device boots, offending symlinks are deleted after reboot.

Change-Id: Id3de00f23a72d84b42b96cdc4c3881e519cc011c
Reviewed-on: https://chromium-review.googlesource.com/1401021
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Mattias Nissler <mnissler@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/init/chromeos_startup b/init/chromeos_startup
--- a/init/chromeos_startup
+++ b/init/chromeos_startup
@@ -500,6 +500,31 @@ for d in /var/cache /var/db /var/empty /var/log /var/log/metrics \
   check_directory "${d}"
 done
 
+# Make sure that what gets written to /var/log stays in /var/log. Some notes on
+# subtleties in the command below:
+#  1. find's -exec with the '+' argument passes multiple found paths per shell
+#     script invocation.
+#  2. sh -c expects a command name before parameters, so we pass a dummy name.
+#     Failure to do so would omit the first symlink since "$0" is not in "$@".
+#  3. set -e causes the shell to bail out on rm failure, so we can err on the
+#     safe side and do a stateful wipe instead of leaving symlinks around.
+#  4. If readlink fails (e.g. due to dangling symlinks) grep will still return
+#     false and so will the pipeline, so dangling symlinks get removed.
+#  5. Find doesn't follow symlinks and we pass -xdev to make sure to only
+#     examine symlinks in the /var/log subtree.
+find /var/log -xdev -type l -exec sh -e -c '
+  for path; do
+    if ! readlink -f "${path}" | grep -q "^/var/log/"; then
+      rm "${path}"
+    fi
+  done
+' 'nuke_symlinks' '{}' '+'
+
+# Bail and wipe on failure to remove a symlink.
+if [ "$?" -ne 0 ]; then
+  cleanup_mounts "Failed to remove symlinks under /var/log"
+fi
+
 # /var/tmp must be world-writable and sticky
 chmod 1777 /var/tmp
 # /home/root must be group-writable and sticky
