arc: Make android-sh consistent on ARC and ARCVM
This changes android-sh script by escaping its parameters.
It also runs /system/bin/sh instead of the direct 'adb shell'
to make it consistent with ARC's 'android-sh'.
ARC 'android-sh' can run even before user is logged in.
This also added additional 'logged-in' wait to allow it to run
on logging-in user.

BUG=b:135393913
TEST=called tast's BootstrapCommand() on ARC and ARCVM.

Change-Id: Id48e030e33b2be34a50756c5bc337b7fc57e8e6e
Reviewed-on: https://chromium-review.googlesource.com/1659871
Tested-by: Jason Jeremy Iman <jasongustaman@google.com>
Commit-Ready: Jason Jeremy Iman <jasongustaman@google.com>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/arc/scripts/android-sh-vm b/arc/scripts/android-sh-vm
--- a/arc/scripts/android-sh-vm
+++ b/arc/scripts/android-sh-vm
@@ -7,16 +7,28 @@
 
 # TODO(b/131121671): Change this when cid becomes dynamic.
 target='vsock:5:5555'
+logged_in_file='/run/state/logged-in'
 
 is_connected() {
   [ -n "$(adb devices 2>/dev/null | grep "${target}")" ]
 }
 
-command=
-if [ "$1" = "-c" ]; then
-  shift
-  command=$@
+# The user might still be logging in.
+# The loop below will wait for ~15 seconds at most.
+attempts=0
+while [ "${attempts}" -le 30 ] && [ ! -f "${logged_in_file}" ]; do
+  sleep 0.5
+  : $(( attempts += 1 ))
+done
+
+if [ ! -f "${logged_in_file}" ]; then
+  echo "$0: Could not connect, user is not logged in." >&2
+  exit 1
 fi
+
+# 'adb shell' always passes the command line to /bin/sh, so we need to
+# escape arguments.
+command="$(/usr/bin/printf "%q " "$@")"
 
 # adb tries to create .android in the home directory, pass it
 # a temporary directory instead.
@@ -36,16 +48,17 @@ attempts=0
 while [ "${attempts}" -le 10 ] && ! is_connected; do
   adb connect ${target} >/dev/null
   sleep 0.5
-  attempts=$(( attempts + 1 ))
+  : $(( attempts += 1 ))
 done
 
 if ! is_connected; then
-  echo "$0: Could not connect, is the VM running?"
+  echo "$0: Could not connect, is the VM running?" >&2
   rm -rf "${tmpdir}"
   exit 1
 fi
 
-adb shell ${command}
+# Run /system/bin/sh to be consistent with 'android-sh'.
+adb shell /system/bin/sh "${command}"
 ret=$?
 rm -rf "${tmpdir}"
 exit $ret
