arc: android-sh-vm: Exit properly when cid isn't retrieved.
concierge_client seems to fail sometimes when retrieving CID:
[ERROR:client.cc(384)] Failed to get VM info

Because stderr is redirected to stdout, $CID becomes populated with
"Failed to get VM info", and then adb connect fails in the loop:

adb: usage: adb connect <host>[:<port>]
adb: usage: adb connect <host>[:<port>]
..

Forward stderr to /dev/null instead, and exit when $CID can't be
retrieved.

BUG=b:137339783
TEST=android-sh exits when it can't read CID.

Change-Id: I8c3f1509710cd6f32c99c5694d31e34438bf5e18
Reviewed-on: https://chromium-review.googlesource.com/1697996
Tested-by: Alex Lau <alexlau@chromium.org>
Commit-Ready: Alex Lau <alexlau@chromium.org>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>

diff --git a/arc/scripts/android-sh-vm b/arc/scripts/android-sh-vm
--- a/arc/scripts/android-sh-vm
+++ b/arc/scripts/android-sh-vm
@@ -35,13 +35,23 @@ export HOME="${tmpdir}"
 
 # Concierge dynamically assigns a VSOCK CID for each VM. Ask the service which
 # CID is currently assigned to ARCVM.
-target="vsock:5:5555"
 ID="$(cryptohome --action=status | jq -r '.mounts[0].owner')"
-CID="$(/usr/bin/concierge_client --get_vm_cid --name=arcvm \
-         --cryptohome_id="${ID}" 2>&1)"
-if [ -n "${CID}" ]; then
-  target="vsock:${CID}:5555"
+if [ "$?" != "0" ]; then
+  echo "$0: Failed to get cryptohome ID, exiting."
+  exit 1
 fi
+
+CID="$(/usr/bin/concierge_client --get_vm_cid --name=arcvm \
+         --cryptohome_id="${ID}")"
+if [ "$?" != "0" ]; then
+  echo "$0: Failed to get CID from concierge, exiting."
+  exit 1
+elif [ -z "${CID}" ]; then
+  echo "$0: Empty CID value returned from concierge, exiting."
+  exit 1
+fi
+
+target="vsock:${CID}:5555"
 
 # Try to start the server first if it's not started.
 adb start-server 2>/dev/null
