add incognito mode around the cryptohome environment
Aside: We need to add a whole suite of cryptohome integration tests to the
tracker for the fixit next week.  This is a great example case to use.  If not,
we can add it in tandem with this CL.

TEST=none
BUG=none

Review URL: http://codereview.chromium.org/1126006

diff --git a/cryptohome/bin/mount b/cryptohome/bin/mount
--- a/cryptohome/bin/mount
+++ b/cryptohome/bin/mount
@@ -12,8 +12,9 @@ PASSWORD=""
 function error_handler() {
   if ! typeset -F cryptohome::log; then
     echo "An error occurred before/in cryptohome." 1>&2
-    # Assume common is ok.
-    /bin/mount -t tmpfs tmpfs $DEFAULT_MOUNT_POINT
+    # Assume common is ok, but maybe not mount options
+    /bin/mount -t tmpfs "$INCOGNITO_MOUNT_NAME" \
+      -onoexec,nosuid,nodev "$DEFAULT_MOUNT_POINT"
     /bin/chown $DEFAULT_USER $DEFAULT_MOUNT_POINT
     exit 1
   fi
@@ -40,12 +41,23 @@ function error_handler() {
 # TODO: move traps into a single call
 trap error_handler ERR;
 
+function incognito_error() {
+  cryptohome::log "failed to mount incognito!"
+  $exit 1
+}
+
+function incognito_mount() {
+  trap incognito_error ERR;
+  $mount -t tmpfs -o"${MOUNT_OPTIONS}" "$INCOGNITO_MOUNT_NAME" \
+    $DEFAULT_MOUNT_POINT
+  $chown ${DEFAULT_USER}:${DEFAULT_USER} $DEFAULT_MOUNT_POINT
+  cryptohome::log "incognito mount completed"
+}
+
 function second_chance() {
   cryptohome::log "new image creation failed (again)"
-  cryptohome::log "mounting tmpfs"
-  $mount -t tmpfs tmpfs $DEFAULT_MOUNT_POINT
-  $chown $DEFAULT_USER $DEFAULT_MOUNT_POINT
-  cryptohome::log "mount completed"
+  cryptohome::log "falling back to incognito mode"
+  incognito_mount
   $exit 0
 }
 
@@ -70,6 +82,11 @@ function mount_main() {
   # login so that we don't blow away old logs during a debug login.
   $exec 1>$STDOUT_FILE
   $exec 2>$STDERR_FILE
+  if [[ "$CHROMEOS_USER" == "$INCOGNITO_USER" ]]; then
+    cryptohome::log "incognito mode requested"
+    incognito_mount
+    $exit 0
+  fi
   USERID="$($cat $IMAGE_DIR/salt <($echo -n $CHROMEOS_USER) | $openssl sha1)"
   PASSWORD="$($cat)"
   cryptohome::mount_or_create "$USERID" "$PASSWORD"
