power: Update powerd_suspend script to use two-space indent.
Update powerd's powerd_suspend helper script to use
two-space indenting (per the Google shell style guide)
rather than four-space indenting.

BUG=chrome-os-partner:60548
TEST=it still works

Change-Id: Id58130ddd4b4714dfcb10ff32e24af42cb0562bf
Reviewed-on: https://chromium-review.googlesource.com/417287
Commit-Ready: Dan Erat <derat@chromium.org>
Tested-by: Dan Erat <derat@chromium.org>
Reviewed-by: Dan Erat <derat@chromium.org>

diff --git a/power_manager/powerd/powerd_suspend b/power_manager/powerd/powerd_suspend
--- a/power_manager/powerd/powerd_suspend
+++ b/power_manager/powerd/powerd_suspend
@@ -10,11 +10,11 @@
 . /usr/share/misc/shflags
 
 DEFINE_integer wakeup_count -1 \
-    "wakeup event count from start of suspend. -1 to disable" w
+  "wakeup event count from start of suspend. -1 to disable" w
 DEFINE_integer suspend_duration -1 \
-    "indicates that the system should wake up after this many seconds" d
+  "indicates that the system should wake up after this many seconds" d
 DEFINE_boolean suspend_to_idle false \
-    "indicates that the system should suspend to idle (freeze)" i
+  "indicates that the system should suspend to idle (freeze)" i
 
 # Exit codes returned by this script and reported via the
 # Power.SuspendResult histogram:
@@ -65,58 +65,58 @@ readonly ROOT_SPOOL_DIR=/var/spool/power_manager/root
 readonly SUSPEND_TO_RAM_TIME_FILE=${ROOT_SPOOL_DIR}/suspend-to-ram-time
 
 log_msg() {
-    logger -t "powerd_suspend[$$]" -- "$@"
+  logger -t "powerd_suspend[$$]" -- "$@"
 }
 
 log_msg_from_file() {
-    logger -t "powerd_suspend[$$]" -f "$1"
+  logger -t "powerd_suspend[$$]" -f "$1"
 }
 
 log_wakeup_count() {
-    log_msg "wakeup_count is $(cat /sys/power/wakeup_count)"
+  log_msg "wakeup_count is $(cat /sys/power/wakeup_count)"
 }
 
 enable_debug() {
-    # Enable debug info.
-    if [ -e /sys/module/printk/parameters/console_suspend ]; then
-        echo -n 'N' > /sys/module/printk/parameters/console_suspend
-    fi
-    if [ -e /sys/power/pm_print_times ]; then
-        echo -n '1' > /sys/power/pm_print_times
-    fi
+  # Enable debug info.
+  if [ -e /sys/module/printk/parameters/console_suspend ]; then
+    printf 'N' > /sys/module/printk/parameters/console_suspend
+  fi
+  if [ -e /sys/power/pm_print_times ]; then
+    printf '1' > /sys/power/pm_print_times
+  fi
 }
 
 is_lumpy() {
-    crossystem hwid | grep -q "LUMPY"
+  crossystem hwid | grep -q "LUMPY"
 }
 
 # Checks if the system has a Novatel Wireless Gobi 3000 E396/E396U modem.
 has_gobi_modem() {
-    lsusb -d 1410:a021 || lsusb -d 1410:a023
+  lsusb -d 1410:a021 || lsusb -d 1410:a023
 }
 
 # Toggles the power and off GPIOs connected to gobi modem in order to
 # revive it.
 do_lumpy_gobi_modem_revive() {
-    cd /sys/class/gpio
+  cd /sys/class/gpio
 
-    # TODO(snanda): Get the gpio base from crossystem instead of assuming
-    # that it will always be 160 for lumpy.
-    if [ ! -d gpio198 ]; then
-        echo 198 > export
-    fi
-    if [ ! -d gpio203 ]; then
-        echo 203 > export
-    fi
+  # TODO(snanda): Get the gpio base from crossystem instead of assuming
+  # that it will always be 160 for lumpy.
+  if [ ! -d gpio198 ]; then
+    echo 198 > export
+  fi
+  if [ ! -d gpio203 ]; then
+    echo 203 > export
+  fi
 
-    echo out > gpio198/direction
-    echo out > gpio203/direction
+  echo out > gpio198/direction
+  echo out > gpio203/direction
 
-    echo 1 > gpio203/value
-    echo 0 > gpio198/value
+  echo 1 > gpio203/value
+  echo 0 > gpio198/value
 
-    echo 0 > gpio203/value
-    echo 1 > gpio198/value
+  echo 0 > gpio203/value
+  echo 1 > gpio198/value
 }
 
 # Blaze modems need to be powered off (MODEM_EN low) when suspending and
@@ -124,57 +124,57 @@ do_lumpy_gobi_modem_revive() {
 
 # Return true on Blaze systems.
 is_blaze() {
-    crossystem hwid | grep -q "BLAZE"
+  crossystem hwid | grep -q "BLAZE"
 }
 
 # Checks if the system has a Huawei Technologies Mobile Broadband Module.
 has_huawei_modem() {
-    lsusb -d 12d1:15bb
+  lsusb -d 12d1:15bb
 }
 
 # Drive the Blaze MODEM_EN gpio for $1 "on" or "off".
 do_blaze_huawei_modem() {
-    gpioval=1
-    [ "$1" = off ] && gpioval=0
+  gpioval=1
+  [ "$1" = off ] && gpioval=0
 
-    cd /sys/class/gpio
-    if [ ! -d gpio148 ]; then
-        echo 148 > export
-    fi
-    echo out > gpio148/direction
-    echo $gpioval > gpio148/value
-    if [ $? -eq 0 ]; then
-        log_msg "Power $1 Huawei modem"
-    else
-        log_msg "Failed to power $1 Huawei modem"
-    fi
+  cd /sys/class/gpio
+  if [ ! -d gpio148 ]; then
+    echo 148 > export
+  fi
+  echo out > gpio148/direction
+  echo $gpioval > gpio148/value
+  if [ $? -eq 0 ]; then
+    log_msg "Power $1 Huawei modem"
+  else
+    log_msg "Failed to power $1 Huawei modem"
+  fi
 }
 
 # Writes the wakeup count that was passed to this script to
 # /sys/power/wakeup_count.  Returns success if the write fails, indicating
 # that one or more wakeup events occurred in the meantime.
 saw_wakeup_event() {
-    if [ "${FLAGS_wakeup_count}" -eq -1 ] ||
-       echo "${FLAGS_wakeup_count}" > "/sys/power/wakeup_count"; then
-        return 1
-    else
-        log_msg "Aborting suspend, wake event received"
-        log_wakeup_count
-        return 0
-    fi
+  if [ "${FLAGS_wakeup_count}" -eq -1 ] ||
+    echo "${FLAGS_wakeup_count}" > "/sys/power/wakeup_count"; then
+    return 1
+  else
+    log_msg "Aborting suspend, wake event received"
+    log_wakeup_count
+    return 0
+  fi
 }
 
 
 # Sends suspend result (one of the above RESULT_* values) to UMA.
 send_uma_result() {
-    metrics_client -e Power.SuspendResult $1 $RESULT_MAX &
+  metrics_client -e Power.SuspendResult $1 $RESULT_MAX &
 }
 
 setup_dark_resume() {
-    if [ "${FLAGS_suspend_duration}" -ne -1 ]; then
-        echo 0 > /sys/class/rtc/rtc0/wakealarm
-        echo "+${FLAGS_suspend_duration}" > /sys/class/rtc/rtc0/wakealarm
-    fi
+  if [ "${FLAGS_suspend_duration}" -ne -1 ]; then
+    echo 0 > /sys/class/rtc/rtc0/wakealarm
+    echo "+${FLAGS_suspend_duration}" > /sys/class/rtc/rtc0/wakealarm
+  fi
 }
 
 # Encourage people to use powerd_dbus_suspend instead of running this
@@ -199,32 +199,32 @@ metrics_client -e Power.SuspendAttempt 0 2 &
 
 # Log the time before going to suspend (no-op if no RTC).
 cp /sys/class/rtc/rtc0/since_epoch $SUSPEND_TO_RAM_TIME_FILE \
-    2> /dev/null || true
+  2> /dev/null || true
 
 # Remove last_resume_timings to ensure the file is fresh on resume.
 rm -f $LAST_RESUME_TIMINGS_FILE
 
 # Store the current power status.
 power_supply_info 2> /dev/null \
-    | /bin/grep -Eq '^[[:space:]]+online:[[:space:]]+no$'
+  | /bin/grep -Eq '^[[:space:]]+online:[[:space:]]+no$'
 if [ $? -eq 0 ]; then
-    echo OnBattery > $POWER_STATUS_ON_SUSPEND_FILE
+  echo OnBattery > $POWER_STATUS_ON_SUSPEND_FILE
 else
-    echo OnAC > $POWER_STATUS_ON_SUSPEND_FILE
+  echo OnAC > $POWER_STATUS_ON_SUSPEND_FILE
 fi
 
 # Is this a Lumpy system with Gobi modem?
 lumpy_with_gobi_modem=0
 if is_lumpy && has_gobi_modem; then
-    log_msg "Lumpy with gobi modem"
-    lumpy_with_gobi_modem=1
+  log_msg "Lumpy with gobi modem"
+  lumpy_with_gobi_modem=1
 fi
 
 # Is this a Blaze system with Huawei modem?
 blaze_with_huawei_modem=0
 if is_blaze && has_huawei_modem; then
-    log_msg "Blaze with Huawei modem"
-    blaze_with_huawei_modem=1
+  log_msg "Blaze with Huawei modem"
+  blaze_with_huawei_modem=1
 fi
 
 enable_debug
@@ -235,97 +235,98 @@ sync
 result=$RESULT_FAILURE
 
 if saw_wakeup_event; then
-    # Note: The client/cros/power_suspend.py module in autotest depends on
-    # this message.
-    log_msg "Cancel suspend at kernel"
+  # Note: The client/cros/power_suspend.py module in autotest depends on
+  # this message.
+  log_msg "Cancel suspend at kernel"
 
-    # This file is usually removed by send_metrics_on_resume, but that script
-    # isn't run if the suspend attempt is unsuccessful.
-    rm -f $SUSPEND_TO_RAM_TIME_FILE
+  # This file is usually removed by send_metrics_on_resume, but that script
+  # isn't run if the suspend attempt is unsuccessful.
+  rm -f $SUSPEND_TO_RAM_TIME_FILE
 
-    result=$RESULT_CANCELED_EARLY
+  result=$RESULT_CANCELED_EARLY
 else
-    # Before suspending, power down this problematic modem.
-    if [ $blaze_with_huawei_modem -eq 1 ]; then
-        do_blaze_huawei_modem off
-    fi
+  # Before suspending, power down this problematic modem.
+  if [ $blaze_with_huawei_modem -eq 1 ]; then
+    do_blaze_huawei_modem off
+  fi
 
-    log_msg "Finalizing suspend"
-    # Make sure that hwclock is cached for when we wake up, this way we don't
-    # wait for io and get a more accurate time for wakeup
-    # -V prints a little version information and exits, loading .so but not
-    # making actual RTC accesses. Do *NOT* change this to a normal execution...
-    # it will trigger an RTC interrupt that may count as a wakeup reason, abort
-    # your suspend and cause you hours of pain and confusion!
+  log_msg "Finalizing suspend"
+  # Make sure that hwclock is cached for when we wake up, this way we don't
+  # wait for io and get a more accurate time for wakeup
+  # -V prints a little version information and exits, loading .so but not
+  # making actual RTC accesses. Do *NOT* change this to a normal execution...
+  # it will trigger an RTC interrupt that may count as a wakeup reason, abort
+  # your suspend and cause you hours of pain and confusion!
+  if [ -f "${TIMESTAMP_FILE}" ]; then
+    /sbin/hwclock -V > /dev/null
+  else
+    # We don't want to overwrite the alarm for whatever test might be
+    # running.
+    setup_dark_resume
+  fi
+
+  # Echo freeze to /sys/power/state on platforms that support suspend to idle.
+  action="mem"
+  if [ ${FLAGS_suspend_to_idle} -eq 0 ]; then
+    action="freeze"
+  fi
+
+  # Suspend to RAM. This is piped through cat since we want to determine
+  # the causes of failures -- dash's "echo" command appears to not print
+  # anything in response to write errors.
+  error=$( (echo -n ${action} | cat > /sys/power/state) 2>&1)
+  if [ $? = 0 ]; then
+    # On resume:
+    result=$RESULT_SUCCESS
+
     if [ -f "${TIMESTAMP_FILE}" ]; then
-        /sbin/hwclock -V > /dev/null
+      # Record the hwclock time at resume for the power_Resume test.
+      TIME=$(/sbin/hwclock --utc)
+      echo ${TIME} > "${TIMESTAMP_FILE}"
+      log_msg "Recorded hwclock time for test"
+    fi
+
+    if [ -e "/sys/firmware/log" ]; then
+      # Grep /sys/firmware/log for WAK
+      wakeup_source=$(grep -A1 -B1 "PM1_STS: WAK" /sys/firmware/log)
+      if [ -z "${wakeup_source}" ]; then
+        wakeup_source="unknown"
+      fi
+      log_msg "wake source: ${wakeup_source}"
+    fi
+
+    # Send UMA metrics.
+    send_metrics_on_resume &
+
+    # Revive the modem if it was present prior to suspending but is absent
+    # now.
+    if [ $lumpy_with_gobi_modem -eq 1 ]; then
+      if ! has_gobi_modem ; then
+        log_msg "Reviving lumpy gobi modem"
+        do_lumpy_gobi_modem_revive
+      fi
+    fi
+
+    # Power back on the Huawei modem.
+    if [ $blaze_with_huawei_modem -eq 1 ]; then
+      do_blaze_huawei_modem on
+    fi
+  else
+    # The write will fail with EBUSY if additional wakeup events have
+    # occurred since the earlier write to /sys/power/wakeup_count.
+    if echo "${error}" | grep -q 'Device or resource busy'; then
+      log_msg "Warning: Device or resource busy on write to /sys/power/state"
+      log_msg_from_file /sys/kernel/debug/suspend_stats
+      log_wakeup_count
+      result=$RESULT_CANCELED_LATE
     else
-        # We don't want to overwrite the alarm for whatever test might be
-        # running.
-        setup_dark_resume
+      # Note: The client/cros/power_suspend.py module in autotest depends on
+      # this message.
+      log_msg "Error writing to /sys/power/state: ${error}"
+      log_msg_from_file /sys/kernel/debug/suspend_stats
+      result=$RESULT_FAILURE
     fi
-
-    # Echo freeze to /sys/power/state on platforms that support suspend to idle.
-    action="mem"
-    if [ ${FLAGS_suspend_to_idle} -eq 0 ]; then
-        action="freeze"
-    fi
-
-    # Suspend to RAM. This is piped through cat since we want to determine
-    # the causes of failures -- dash's "echo" command appears to not print
-    # anything in response to write errors.
-    error=$( (echo -n ${action} | cat > /sys/power/state) 2>&1)
-    if [ $? = 0 ]; then
-        # On resume:
-        result=$RESULT_SUCCESS
-
-        if [ -f "${TIMESTAMP_FILE}" ]; then
-            # Record the hwclock time at resume for the power_Resume test.
-            TIME=$(/sbin/hwclock --utc)
-            echo ${TIME} > "${TIMESTAMP_FILE}"
-            log_msg "Recorded hwclock time for test"
-        fi
-
-        if [ -e "/sys/firmware/log" ]; then
-            # Grep /sys/firmware/log for WAK
-            wakeup_source=$(grep -A1 -B1 "PM1_STS: WAK" /sys/firmware/log)
-            if [ -z "${wakeup_source}" ]; then
-                wakeup_source="unknown"
-            fi
-            log_msg "wake source: ${wakeup_source}"
-        fi
-
-        # Send UMA metrics.
-        send_metrics_on_resume &
-
-        # Revive the modem if it was present prior to suspending but is absent
-        # now.
-        if [ $lumpy_with_gobi_modem -eq 1 ]; then
-            if ! has_gobi_modem ; then
-                log_msg "Reviving lumpy gobi modem"
-                do_lumpy_gobi_modem_revive
-            fi
-        fi
-
-        # Power back on the Huawei modem.
-        if [ $blaze_with_huawei_modem -eq 1 ]; then
-            do_blaze_huawei_modem on
-        fi
-    else
-        # The write will fail with EBUSY if additional wakeup events have
-        # occurred since the earlier write to /sys/power/wakeup_count.
-        if echo "${error}" | grep -q 'Device or resource busy'; then
-            log_msg "Warning: Device or resource busy while writing to " \
-                    "/sys/power/state"
-            log_msg_from_file /sys/kernel/debug/suspend_stats
-            log_wakeup_count
-            result=$RESULT_CANCELED_LATE
-        else
-            log_msg "Error writing to /sys/power/state: ${error}"
-            log_msg_from_file /sys/kernel/debug/suspend_stats
-            result=$RESULT_FAILURE
-        fi
-    fi
+  fi
 fi
 
 send_uma_result $result
