power: power off/on Huawei ME936 modem on Kip during suspend/resume
CL:324106 modified powerd_suspend to power off the Huawei ME936 modem on
Blaze before the system goes to suspend and power the modem on after the
system resumes from suspend. The same modem is used on Kip and would be
affected by chrome-os-partner:48653. This CL ports CL:324106 to work on
Kip. Unlike Blaze that has a kernel accessible GPIO to toggle the modem
power, we need to toggle the modem power on Kip over EC using the
`ectool wireless` command, which introduces a dependency on
chromeos-base/ec-utils to chromeos-base/power_manager when building with
the cellular feature (i.e. USE=cellular).

BUG=chrome-os-partner:48653
CQ-DEPEND=CL:430071
TEST=Verified that the ME936 modem is powered off on Kip before the
     system goes into suspend and then powered on again after the system
     resumes from suspend.

Change-Id: I856e055e581f51a83b47cc00476c1883a9f26b58
Reviewed-on: https://chromium-review.googlesource.com/429931
Commit-Ready: Ben Chan <benchan@chromium.org>
Tested-by: Ben Chan <benchan@chromium.org>
Reviewed-by: Dan Erat <derat@chromium.org>

diff --git a/power_manager/powerd/powerd_suspend b/power_manager/powerd/powerd_suspend
--- a/power_manager/powerd/powerd_suspend
+++ b/power_manager/powerd/powerd_suspend
@@ -141,6 +141,10 @@ is_blaze() {
   crossystem hwid | grep -q "BLAZE"
 }
 
+is_kip() {
+  crossystem hwid | grep -q '^KIP '
+}
+
 # Checks if the system has a Huawei Technologies Mobile Broadband Module.
 has_huawei_modem() {
   lsusb -d 12d1:15bb
@@ -161,6 +165,32 @@ do_blaze_huawei_modem() {
     log_msg "Power $1 Huawei modem"
   else
     log_msg "Failed to power $1 Huawei modem"
+  fi
+}
+
+# Powers "on" or "off" the built-in modem via EC.
+ec_power_modem() {
+  local op="$1"
+
+  case "${op}" in
+    on)
+      ectool wireless 0x4 0x4
+      ;;
+    off)
+      ectool wireless 0x0 0x4
+      ;;
+    *)
+      log_msg "Invalid operation 'ec_power_modem ${op}'"
+      return 1
+      ;;
+  esac
+
+  if [ $? -eq 0 ]; then
+    log_msg "Power ${op} built-in modem"
+    return 0
+  else
+    log_msg "Failed to power ${op} built-in modem"
+    return 1
   fi
 }
 
@@ -241,6 +271,13 @@ if is_blaze && has_huawei_modem; then
   blaze_with_huawei_modem=1
 fi
 
+# Is this a Kip system with Huawei modem?
+kip_with_huawei_modem=0
+if is_kip && has_huawei_modem; then
+  log_msg "Kip with Huawei modem"
+  kip_with_huawei_modem=1
+fi
+
 enable_debug
 
 log_msg "Explicit sync"
@@ -262,6 +299,9 @@ else
   # Before suspending, power down this problematic modem.
   if [ $blaze_with_huawei_modem -eq 1 ]; then
     do_blaze_huawei_modem off
+  fi
+  if [ ${kip_with_huawei_modem} -eq 1 ]; then
+    ec_power_modem off
   fi
 
   log_msg "Finalizing suspend"
@@ -340,6 +380,9 @@ else
   # Power back on the Huawei modem if it was powered off before suspend.
   if [ $blaze_with_huawei_modem -eq 1 ]; then
     do_blaze_huawei_modem on
+  fi
+  if [ ${kip_with_huawei_modem} -eq 1 ]; then
+    ec_power_modem on
   fi
 fi
 
