init: Copy previously removed code from regular startup back into embedded.
This is a step towards eliminating the differences between regular and
embedded startup so that they can be unified. The code is copied from
init/chromeos_startup without any modifications.

BUG=chromium:221343
TEST=booted daisy-drm image, ensured chromeos_startup runs to
completion by checking for bootstat's post-startup stamp.

Change-Id: I5452182d41b50c951728fb89001c7ab73c3f77f2
Reviewed-on: https://gerrit.chromium.org/gerrit/51441
Tested-by: Darin Petkov <petkov@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Darin Petkov <petkov@chromium.org>

diff --git a/init/embedded-init/chromeos_startup b/init/embedded-init/chromeos_startup
--- a/init/embedded-init/chromeos_startup
+++ b/init/embedded-init/chromeos_startup
@@ -12,6 +12,14 @@ mount -n -t tmpfs -o nodev,noexec,nosuid tmp /tmp
 mount -n -t debugfs -o nodev,noexec,nosuid,mode=0750,uid=0,gid=debugfs-access \
   debugfs /sys/kernel/debug
 
+# bootstat writes timings to both tmpfs and debugfs.
+bootstat pre-startup
+
+IS_FACTORY_MODE=
+if [ -f /root/.factory_test -o -f /root/.factory_installer ]; then
+  IS_FACTORY_MODE=1
+fi
+
 mkdir -p /dev/shm /dev/pts
 mount -n -t tmpfs -o nodev,noexec,nosuid shmfs /dev/shm
 mount -n -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts
@@ -76,7 +84,138 @@ if [ $(date +%Y) -lt 1970 ]; then
   date 010200001970.00
 fi
 
-# A bunch of dev mode, debug stuff.  Stateful update, firmware update, etc.
+# DEV_MODE is used to determine if we're booted in developer mode,
+# by checking only the developer and recovery switch states.
+# Values:
+# 0=recovery/non-dev mode,
+# 1=dev (SSD) mode,
+# 2=we've rebooted to handle a request for stateful wipe because of
+#   factory or power wash.
+# Of these the check below assigns 0 or 1. The remaining value(s) will
+# be assigned later.
+crossystem "devsw_boot?1" && ! crossystem "mainfw_act?recovery"
+DEV_MODE=$((! $?))
+
+# CROS_DEBUG equals one if we've booted in developer mode or we've booted a
+# developer image.
+crossystem "cros_debug?1"
+CROS_DEBUG=$((! $?))
+
+# Check if we need to perform firmware update: only if fwupdate_tries is
+# non-zero or if not using normal (ex, developer or recovery) firmware.
+FIRMWARE_UPDATE_SCRIPT=/usr/sbin/chromeos-firmwareupdate
+if ! crossystem "fwupdate_tries?0" "mainfw_type?normal" &&
+   [ -x "$FIRMWARE_UPDATE_SCRIPT" ]; then
+  # This file will be collected by chromeos-setgoodkernel
+  FIRMWARE_UPDATE_LOGS=/mnt/stateful_partition/update_firmware.log
+  tries="$(crossystem fwupdate_tries || echo 0)"
+
+  # Special updating rules for legacy systems.
+  case "$(mosys platform name 2>/dev/null)" in
+    Alex | ZGB )
+      if [ "$(crossystem mainfw_type)" = developer ]; then
+        tries=0  # Prevents updates if we're in developer mode
+        chromeos-boot-alert dev_fwcheck /dev/tty1
+      fi
+      ;;
+  esac
+
+  if [ $tries -gt 0 ]; then
+    crossystem fwupdate_tries=$((tries - 1))
+    # More messages on console for developer mode and dev builds.
+    [ "$CROS_DEBUG" = "1" ] &&
+      FIRMWARE_UPDATE_LOGS="/dev/tty1 $FIRMWARE_UPDATE_LOGS" || true
+    chromeos-boot-alert update_firmware /dev/tty1
+    (date && "$FIRMWARE_UPDATE_SCRIPT" --mode=startup 2>&1) |
+      tee -a $FIRMWARE_UPDATE_LOGS
+    # Sends "clear screen" terminal command to clear TTY frame buffer, to
+    # prevent user seeing the messages again on system shutdown.
+    [ "$CROS_DEBUG" = 1 ] && tput clear >/dev/tty1 || true
+  fi
+fi
+
+# If we've switched from verified mode to developer mode, clobber the state.
+# The reverse is not possible to detect reliably, but we try.
+# In addition, normal and unsupported are treated are equivalent otherwise
+# booting the first time on a legacy device would clobber state for no reason.
+# (NOTE, this will not be triggered in recovery mode.)
+
+# File used to trigger a stateful reset
+RESET_FILE="/mnt/stateful_partition/factory_install_reset"
+
+# File defined by clobber-state
+DEV_MODE_FILE="/mnt/stateful_partition/.developer_mode"
+
+# If in factory mode or a wipe process is already scheduled,
+# set DEV_MODE to 2 so that the right thing happens later.
+if [ -n "$IS_FACTORY_MODE" -o -O "$RESET_FILE" ]; then
+  DEV_MODE=2
+fi
+
+if [ ${DEV_MODE} -eq 1 ]; then
+  FW_TYPE=$(crossystem mainfw_type)
+  # For platforms using separated normal/developer firmware, we need to display
+  # an extra page for developer mode warning.
+  if [ "${FW_TYPE}" != "developer" ]; then
+    chromeos-boot-alert warn_dev /dev/tty1
+  fi
+fi
+
+# Check if we have an update to stateful pending.
+# Note:  THIS MUST BE DONE BEFORE CLOBBER STATE.
+STATEFUL_UPDATE="/mnt/stateful_partition/.update_available"
+if [ -f "$STATEFUL_UPDATE" ] ; then
+  # To remain compatible with the prior update_stateful tarballs, expect
+  # the "var_new" unpack location, but move it into the new "var_overlay"
+  # target location.
+  VAR_TARGET="/mnt/stateful_partition/var"
+  VAR_NEW="${VAR_TARGET}_new"
+  VAR_OLD="${VAR_TARGET}_old"
+  VAR_TARGET="${VAR_TARGET}_overlay"
+  DEVELOPER_TARGET="/mnt/stateful_partition/dev_image"
+  DEVELOPER_NEW="${DEVELOPER_TARGET}_new"
+  DEVELOPER_OLD="${DEVELOPER_TARGET}_old"
+  STATEFUL_UPDATE_ARGS=$(cat "$STATEFUL_UPDATE")
+  # Remove old state in case this process got interrupted by a reset, this is
+  # usually a no-op.
+  rm -rf "$DEVELOPER_OLD" "$VAR_OLD"
+  # The moves can fail if they were previously interrupted mid-op.
+  mv "$DEVELOPER_TARGET" "$DEVELOPER_OLD" || true
+  mv "$VAR_TARGET" "$VAR_OLD" || true
+  mv "$DEVELOPER_NEW" "$DEVELOPER_TARGET" || true
+  mv "$VAR_NEW" "$VAR_TARGET" || true
+  # Check for clobber.
+  if [ "$STATEFUL_UPDATE_ARGS" = "clobber" ]; then
+    # Removes all dirs except the new dev_image and var_overlay.
+    find /mnt/stateful_partition -mindepth 1 -maxdepth 1 |
+      grep -v -e dev_image\$ -e var_overlay\$ |
+      xargs -d "\n" rm -rf
+    # Let's really be done before coming back.
+    sync
+  else
+    # Backgrounded to take off boot path.
+    rm -rf "$STATEFUL_UPDATE" "$DEVELOPER_OLD" "$VAR_OLD" &
+  fi
+fi
+
+# Check if the stateful partition has requested self-destruction. If DEV_MODE is
+# 0 or 1, we've already displayed the correct localized image earlier. The only
+# case we've to handle is when DEV_MODE is 2.
+# If it's after factory finalization, then the wipe_splash.png should be used
+# to display the message. This image will contain the text to display as per
+# the factory's locale. Otherwise, we display the powerwash message.
+if [ -O "$RESET_FILE" ]; then
+  if [ ${DEV_MODE} -eq 2 ]; then
+    ALTERNATE_WIPE_SCREEN=/mnt/stateful_partition/wipe_splash.png
+    if [ -O "$ALTERNATE_WIPE_SCREEN" ]; then
+      chromeos-boot-alert wipe /dev/tty1 "$ALTERNATE_WIPE_SCREEN"
+    else
+      chromeos-boot-alert power_wash /dev/tty1
+    fi
+  fi
+  ARGS="$(cat ${RESET_FILE})"
+  exec clobber-state "$ARGS"
+fi
 
 # Make sure unencrypted stateful partition has the needed directories.
 for d in home home/chronos home/root home/user \
@@ -152,6 +291,8 @@ if [ "$CROS_DEBUG" = "1" -o -f /root/.dev_mode ]; then
     done
   fi
 fi
+
+bootstat post-startup
 
 # Always return success to avoid killing init
 exit 0
