Added an "update-prl" command to the modem script. This results in the crosh "modem" command now having an update-prl option. It takes a single argument, which is the pathname of the PRL file.
BUG=chromium-os:9172
TEST=Ran both /usr/bin/modem and the crosh modem command to switch
back and forth between VZW PRL versions 58008 and 56007, and verified
that when the modem object reappeared, the correct PRL version was
reported. Tried running the new command while the modem was in GSM
mode, and as expected, it failed because it couldn't get the values
of MDN and MIN.

Change-Id: I49c30cd608097cb2ae1d4c892c3dca84f6d94647

Review URL: https://chromereview.prom.corp.google.com/2391012

diff --git a/gobi-cromo-plugin/modem b/gobi-cromo-plugin/modem
--- a/gobi-cromo-plugin/modem
+++ b/gobi-cromo-plugin/modem
@@ -55,6 +55,22 @@ status () {
 	/usr/share/userfeedback/scripts/mm-status
 }
 
+update_prl () {
+	local modem
+	local mdn
+	local min
+	$(needarg prlfile)
+	modem=$(modems | head -1)
+	[ -z "$modem" ] && echo "no modem found" && exit 1
+	mdn=$(dbus $modem $IMODEM_SIMPLE.GetStatus | awk '/\/mdn/ {print $2}')
+	min=$(dbus $modem $IMODEM_SIMPLE.GetStatus | awk '/\/min/ {print $2}')
+	if [ -z "$mdn" -o -z "$min" ]; then
+		echo "Cannot update PRL: MDN/MIN are unknown"
+		exit 1
+	fi
+	activate_manual $modem mdn $mdn min $min prlfile $prlfile
+}
+
 usage () {
 	echo "Usage: $0 <command> [args...]"
 	echo "  activate <modem> <carrier>         Activate modem"
@@ -62,6 +78,7 @@ usage () {
 	echo "  connect <modem> [args...]          Connect modem"
 	echo "  factory-reset <modem> <spc>        Factory-reset the modem"
 	echo "  status                             Display modem status"
+        echo "  update-prl <prl-file-name>         Install a PRL file"
 	exit 0
 }
 
@@ -82,6 +99,9 @@ case "$cmd" in
 	status)
 		status "$@"
 		;;
+        update-prl)
+                update_prl "$@"
+                ;;
 	*)
 		usage
 		;;
