Copy PRL file to /tmp before issuing the command to cromo to update the PRL.
The "modem prl-update" command was failing for downloaded PRL files.
This was because the Downloads directory is owned by user "chronos",
and has permissions 700. cromo runs as user "cromo", and therefore
is not able to access the Downloads directory. So even though crosh,
which runs as "chronos", was able to read the file, cromo could not.
The solution is to have the modem script first copy the PRL file into
a public directory, /tmp.

BUG=chromium-os:9172
TEST=Before and after test, in which I tried the modem update-prl
command, giving it a PRL pathname in /home/chronos/user/Download,
and observed that it failed because cromo got Permission Denied
while trying to open the file. After the change was in place, tried
the same command and it worked, and afterwards, a copy of the PRL
file could be found in /tmp.

Change-Id: I0e58f64203109e9376a9cdcf36679b55c17b9f2d

Review URL: https://chromereviews.googleplex.com/2468012

diff --git a/gobi-cromo-plugin/modem b/gobi-cromo-plugin/modem
--- a/gobi-cromo-plugin/modem
+++ b/gobi-cromo-plugin/modem
@@ -68,6 +68,24 @@ update_prl () {
 		echo "Cannot update PRL: MDN/MIN are unknown"
 		exit 1
 	fi
+	if [ ! -r "$prlfile" ]; then
+		echo "Cannot read PRL file \"$prlfile\""
+		exit 1
+	fi
+	# Because cromo runs as a different user than this script,
+	# it may not have access to the specified file, even when
+	# the script does. A specific example is the Downloads folder,
+	# which only the "chronos" user has access to. To work
+	# around this problem, we copy the PRL file to /tmp.
+	if ! echo "$prlfile" | grep -q '^/tmp/'; then
+		prlbase=${prlfile##*/}
+		cp $prlfile /tmp/$prlbase
+		if [ $? -ne 0 ]; then
+			echo "Cannot copy PRL file \"$prlfile\" to temp directory"
+			exit 1
+		fi
+		prlfile=/tmp/$prlbase
+	fi
 	activate_manual $modem mdn $mdn min $min prlfile $prlfile
 }
 
