shill: Adjust permissions in shill_login_user to give shill user access.
Allow network profile and logging files that are stored in
/home/root/<hash> to be accessible to shill user.

BUG=chromium:649417
TEST=log in to guest/user mode, shill can access the appropriate
dirs/files (as can root before we make the final switch).

Change-Id: I374bd5526b3b8dea307343bbddb16a44783900d7
Reviewed-on: https://chromium-review.googlesource.com/1120942
Commit-Ready: Micah Morton <mortonm@chromium.org>
Tested-by: Micah Morton <mortonm@chromium.org>
Reviewed-by: Ben Chan <benchan@chromium.org>

diff --git a/shill/bin/shill_login_user b/shill/bin/shill_login_user
--- a/shill/bin/shill_login_user
+++ b/shill/bin/shill_login_user
@@ -91,12 +91,22 @@ if [ ! -d "$profile_dir" ]; then
     logger -t "$script_name" \
       "Failed to create shill user profile directory $profile_dir"
     exit 1
+  else
+    if ! chown shill:shill "$profile_dir" ; then
+      logger -t "$script_name" \
+        "Failed to chown shill user profile directory $profile_dir"
+      exit 1
+    fi
   fi
 fi
 
 if ! mkdir -p --mode 0700 "$profile_link_root"; then
   logger -t "$script_name" \
     "Unable to create shill user profile link directory"
+else
+  if ! chown shill:shill "$profile_link_root"; then
+    logger -t "$script_name" "Unable to chown shill user profile link directory"
+  fi
 fi
 
 ln -s "$profile_dir" "$profile_link_dir" ||
@@ -106,6 +116,10 @@ ln -s "$profile_dir" "$profile_link_dir" ||
 if ! mkdir -p --mode 0700 "$log_dir"; then
   logger -t "$script_name" \
     "Unable to create shill log directory"
+else
+  if ! chown shill:shill "$log_dir"; then
+    logger -t "$script_name" "Unable to chown shill log directory"
+  fi
 fi
 
 if [ ! -h "$log_link_dir" ]; then
