Added a 'chaps_debug' command to set the chaps log level.
BUG=chromium-os:30835
TEST=Manual

CQ-DEPEND=If74949ffb6c2116528262b70a5e86e7cfd180bdf

Change-Id: I99c552d11fb2488066045bad74130fb16bb5cb5e
Reviewed-on: https://gerrit.chromium.org/gerrit/23002
Commit-Ready: Darren Krahn <dkrahn@chromium.org>
Reviewed-by: Darren Krahn <dkrahn@chromium.org>
Tested-by: Darren Krahn <dkrahn@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -107,6 +107,9 @@ HELP_ADVANCED='
 
  syslog <message>
   Logs a message to syslog.
+
+ chaps_debug [start|stop|<log_level>]
+  Sets the chapsd logging level. No arguments will start verbose logging.
 '
 
 CHROMEOS_INSTALL=/usr/sbin/chromeos-install
@@ -707,6 +710,22 @@ cmd_chaps() {
     echo "You must reboot for this to take effect."
   else
     echo "No change."
+  fi
+}
+
+cmd_chaps_debug() {
+  local level=${1:--2}
+  if [ "$1" = "stop" ]; then
+    level=0
+  fi
+  if [ "$1" = "start" ]; then
+    level=-2
+  fi
+  /usr/bin/chaps_client --set_log_level=${level} 2> /dev/null
+  if [ $? -eq 0 ]; then
+    echo "Logging level set to ${level}."
+  else
+    echo "Failed to set logging level."
   fi
 }
 
