crosh: implement command newblue status
Tells whether newblue is enabled/disabled, and whether restart is
required.

BUG=chromium:955017
TEST=newblue status
Cq-Depend: chromium:1583569

Change-Id: I950ec49d25b7cad0811ab166b32bb5a32107a74b
Reviewed-on: https://chromium-review.googlesource.com/1583568
Commit-Ready: Archie Pusaka <apusaka@chromium.org>
Tested-by: Archie Pusaka <apusaka@chromium.org>
Reviewed-by: Sonny Sasaka <sonnysasaka@chromium.org>
Reviewed-by: Chirantan Ekbote <chirantan@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -576,31 +576,47 @@ cmd_bt_console() (
   "${EXEC_bt_console}" "${1:+--agent=$1}"
 )
 
-USAGE_newblue='<enable | disable>'
+USAGE_newblue='< status | enable | disable >'
 HELP_newblue='Set the preference of enabling/disabling the use of Newblue
 Bluetooth stack. In order for the preference to take effect, please login as
 the owner account and go to chrome://flags to enable the "Newblue" flag and
 reboot the device.
 '
 cmd_newblue() (
-  if [ $# -ne 1 ]; then
+  if [ $# -gt 1 ]; then
     help "unexpected number of argument"
     return 1
   fi
 
-  local enabled
+  local enabled reply
 
   case "$1" in
-  enable)
-    enabled="true"
-    ;;
-  disable)
-    enabled="false"
-    ;;
-  *)
-    help "unknown option $1"
-    return 1
-    ;;
+    status|"")
+      reply=$(dbus-send --system --type=method_call --print-reply \
+          --dest=org.bluez /org/bluez \
+          org.chromium.BluetoothExperimental.GetNewblueEnabled)
+
+      if [ $? -ne 0 ]; then
+        echo "ERROR: querying newblue status failed"
+        return 1
+      fi
+
+      # reply will look like this
+      # method return time=xxx sender:yyy ... reply_serial=z string "enabled"
+      # use sed to extract part between the quotes
+      echo "${reply}" | sed -n -E '$s/.*string "(.*)"/\1/p'
+      return
+      ;;
+    enable)
+      enabled="true"
+      ;;
+    disable)
+      enabled="false"
+      ;;
+    *)
+      help "unknown option $1"
+      return 1
+      ;;
   esac
 
   dbus-send --system --type=method_call --dest=org.bluez /org/bluez \
