crosh: Add 'vmc list'
This command allows users to see what VMs they have created.

BUG=703925
TEST='vmc list' from crosh prints the VMs

Change-Id: I0ec4ad6321ff1257d831f47d3446cf6d9fb63dc9
Signed-off-by: Dylan Reid <dgreid@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/947708
Reviewed-by: Stephen Barber <smbarber@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -468,6 +468,13 @@ cmd_vmc() (
       return 1
     fi
     ;;
+  list)
+    concierge_client --list_disks --cryptohome_id="${CROS_USER_ID_HASH}"
+    if [ $? -ne 0 ]; then
+      echo "Unable to list vms"
+      return 1
+    fi
+    ;;
   *)
     echo "Unknown VM command: ${cmd}"
   esac
