crosh: Add command for writting a persistent file for Newblue preference
This add a new command, newblue, for setting the preference of
enabling/disabling the use of Newblue Bluetooth stack.

BUG=chromium:859239
TEST=run newblue command with enable/disable and confirm that the
/var/lib/bluetooth/newblue file is added/removed
CQ-DEPEND=CL:1130837

Change-Id: I7b19bdba3ea93c608eb8cdfc941e3c3d16e9fde6
Reviewed-on: https://chromium-review.googlesource.com/1121542
Commit-Ready: Miao-chen Chou <mcchou@chromium.org>
Tested-by: Miao-chen Chou <mcchou@chromium.org>
Reviewed-by: Sonny Sasaka <sonnysasaka@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -658,6 +658,42 @@ cmd_bt_console() (
   "${EXEC_bt_console}" "${1:+--agent=$1}"
 )
 
+USAGE_newblue='<enable | disable>'
+HELP_newblue='Set the preference of enabling/disabling the use of Newblue
+Bluetooth stack. In order for the preference to take effect, please login as
+the owner account and go to chrome://flags to enable the "Newblue" flag and
+reboot the device.
+'
+cmd_newblue() (
+  if [ $# -ne 1 ]; then
+    help "unexpected number of argument"
+    return 1
+  fi
+
+  local enabled
+
+  case "$1" in
+  enable)
+    enabled="true"
+    ;;
+  disable)
+    enabled="false"
+    ;;
+  *)
+    help "unknown option $1"
+    return 1
+    ;;
+  esac
+
+  dbus-send --system --type=method_call --dest=org.bluez /org/bluez \
+      org.chromium.BluetoothExperimental.SetNewblueEnabled "boolean:${enabled}"
+
+  if [ $? -ne 0 ]; then
+    echo "ERROR: setting newblue status failed"
+    return 1
+  fi
+)
+
 # Set the help string so crosh can discover us automatically.
 HELP_ff_debug=''
 EXEC_ff_debug='/usr/bin/ff_debug'
