crosh: add systrace support for developers
Add a systrace command to control system event logging (via debugd).
This is enabled only in developer mode.

BUG=chromium-os:27809
TEST=enter crosh; systrace start, systrace status, systrace stop

Change-Id: Ia76da4ab88a59e847dbd647f87e47d015b37fd07
Reviewed-on: https://gerrit.chromium.org/gerrit/17148
Reviewed-by: Kees Cook <keescook@chromium.org>
Tested-by: Sam Leffler <sleffler@chromium.org>
Commit-Ready: Sam Leffler <sleffler@chromium.org>

diff --git a/crosh/crosh-dev b/crosh/crosh-dev
--- a/crosh/crosh-dev
+++ b/crosh/crosh-dev
@@ -12,6 +12,15 @@ fi
 DEV_HELP='
  shell
   Open a command line shell.
+
+ systrace [<start | stop | status>]
+  Start/stop system tracing.  Turning tracing off will generate a trace
+  log file in the Downloads directory with all the events collected
+  since the last time tracing was enabled.  One can control the events
+  collected by specifying categories after "start"; e.g. "start gfx"
+  will collect only graphics-related system events.  "systrace status"
+  (or just "systrace") will display the current state of tracing, including
+  the set of events being traced.
 '
 
 HELP="$HELP$DEV_HELP"
@@ -28,4 +37,32 @@ cmd_shell() {
   fi
   exec $SHELL
   )
+}
+
+cmd_systrace() {
+  case x"$1" in
+  xstart)
+    local categories;
+    shift; categories="$*"
+    if [ -z "${categories}" ]; then
+       categories="all"
+    fi
+    debugd SystraceStart "string:${categories}"
+    ;;
+  xstop)
+    local downloads_dir="/home/${USER}/user/Downloads"
+    local data_file=$(mktemp ${downloads_dir}/systrace.XXXX)
+    if [ $? -ne 0 ]; then
+      echo "Cannot create data file ${data_file}"
+      return 1
+    fi
+    debugd SystraceStop "fd:1" > "${data_file}"
+    echo "Trace data saved to ${data_file}"
+    # add symlink to the latest capture file
+    ln -sf $(basename $data_file) ${downloads_dir}/systrace.latest
+    ;;
+  xstatus|x)
+    debugd SystraceStatus
+    ;;
+  esac
 }
