crosh: setup signal traps early
Let's set up the ctrl+c at the very beginning.  We can also use a simpler
form rather than needing a dedicated function.

Similarly, let's also do the HUP handling at the same time.

BUG=None
TEST=ran crosh & hit CTRL+C and saw crosh continue to run
TEST=ran crosh & ran ping & hit CTRL+C and saw ping aborted

Change-Id: Iee4f83ef845374f7962ff905eb3249348d6d435c
Reviewed-on: https://chromium-review.googlesource.com/178934
Reviewed-by: Chris Masone <cmasone@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -11,6 +11,15 @@
 # Please test that any changes continue to work in dash by running
 # '/build/$BOARD/bin/dash crosh --dash' before checking them in.
 
+# Don't allow SIGHUP to terminate crosh. This guarantees that even if the user
+# closes the crosh window, we make our way back up to the main loop, which gives
+# cleanup code in command handlers a chance to run.
+trap '' HUP
+
+# Do not let CTRL+C kill crosh itself.  This does let the user kill commands
+# that are run by crosh (like `ping`).
+trap : INT
+
 IS_BASH=0
 try_bash() {
   # If dash was explicitly requested, then nothing to do.
@@ -217,12 +226,6 @@ DEVMODE=$((!$?))
 if [ "$(echo "$@" | grep -- "--dev")" -o "$DEVMODE" = "1" ]; then
   . "$(dirname "$0")/crosh-dev"
 fi
-
-ctrl_c() {
-  return
-}
-
-trap ctrl_c INT
 
 shell_read() {
   local prompt="$1"
@@ -1423,11 +1426,6 @@ check_username() {
 check_digits() {
   expr "$1" : '^[[:digit:]]*$' > /dev/null
 }
-
-# Don't allow SIGHUP to terminate crosh. This guarantees that even if the user
-# closes the crosh window, we make our way back up to the main loop, which gives
-# cleanup code in command handlers a chance to run.
-trap '' HUP
 
 repl() {
   echo "${INTRO_TEXT}"
