crosh: Do component and concierge setup before vmc commands
Instead of mounting the component and starting concierge in the start
command, do it before running any vmc command. This fixes running list
or destroy before start.

Change-Id: Ib8031d553c6cd49f5a9a46021b5aa65e01d93fcd
Signed-off-by: Dylan Reid <dgreid@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/964714
Reviewed-by: Stephen Barber <smbarber@chromium.org>
Reviewed-by: Chirantan Ekbote <chirantan@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -409,6 +409,19 @@ cmd_vmc() (
     echo "This command is not available."
     return 1
   fi
+
+  # Mount the termina component, waiting up to 2 minutes to download it.  If
+  # this fails we won't be able to start the concierge service below.
+  imageloader --reply-timeout=120000 LoadComponent string:cros-termina
+
+  # Start the concierge service.
+  local reply
+  reply="$(debugd StartVmConcierge)"
+  if [ $? -ne 0 -o "${reply}" != "true" ]; then
+    echo "Unable to start concierge service"
+    return 1
+  fi
+
   local cmd="$1"; shift
   case "${cmd}" in
   start)
@@ -418,18 +431,6 @@ cmd_vmc() (
     fi
 
     local name="$1"; shift
-
-    # Mount the termina component, waiting up to 2 minutes to download it.  If
-    # this fails we won't be able to start the concierge service below.
-    imageloader --reply-timeout=120000 LoadComponent string:cros-termina
-
-    # Start the concierge service.
-    local reply
-    reply="$(debugd StartVmConcierge)"
-    if [ $? -ne 0 -o "${reply}" != "true" ]; then
-      echo "Unable to start concierge service"
-      return 1
-    fi
 
     # Actually start the VM.
     concierge_client --start_termina_vm --name="${name}" \
