crosh: promote container command to main tool
This won't be available on a system unless USE=containers is enabled.

BUG=chromium:665622
TEST=crosh 'c' command still works

Change-Id: Id97bafdba72c4a4c20d91de1cc442fa924f54014
Reviewed-on: https://chromium-review.googlesource.com/506750
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -1449,6 +1449,39 @@ cmd_vmstat() (
   vmstat "$@"
 )
 
+USAGE_c='<container name> [args]'
+HELP_c='
+  Run a program inside a container
+'
+EXEC_c='/usr/bin/run_oci'
+cmd_c() (
+  cleanup() {
+    trap : INT
+    debugd ContainerStopped
+  }
+  trap cleanup INT
+
+  local container="$1"
+  if [ -z "${container}" ]; then
+    echo "No container specified"
+    return 1
+  fi
+  shift
+
+  local mount_dir=$(/usr/bin/mount_extension_image --name="${container}")
+  if [ -z "${mount_dir}" ]; then
+    echo "Could not find container"
+    return 1
+  fi
+  debugd ContainerStarted
+  HOME=/home/user /usr/bin/run_oci \
+    --cgroup_parent=chronos_containers \
+    --bind_mount=/home/chronos/user/Downloads:/home/user \
+    --bind_mount=/run/djfs:/dev \
+    "${mount_dir}" -- "$@"
+  cleanup
+)
+
 substr() {
   local str="$1"
   local start="$2"
