crosh: trap SIGHUP
Trapping SIGHUP ensures that we always make it back to the main loop when our
window is closed, which gives cleanup code in helpers a chance to run.

BUG=None
TEST=Adhoc
Build, run crosh, kill the window, see the crosh process is properly dead.

Change-Id: I95cdec47da27f4d572ef767eeca5fb22b3857948
Signed-off-by: Elly Jones <ellyjones@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/12574

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -791,6 +791,11 @@ check_digits() {
   expr "$1" : '^[[:digit:]]*$' > /dev/null
 }
 
+# Don't allow SIGHUP to terminate crosh. This guarantees that even if the user
+# closes the crosh window, we make our way back up to the main loop, which gives
+# cleanup code in command handlers a chance to run.
+trap '' HUP
+
 repl() {
   echo "Welcome to crosh, type 'help' for a list of commands."
   if [ "$IS_BASH" != "1" ]; then
