Add "packet_capture" as a dev command in crosh
Add a dev-mode-only "packet_capture" command that uses debugd
to run a device-based or monitored packet capture.

CQ-DEPEND=CL:50010
BUG=chromium:218380
TEST=manual tests on a daisy with a USB WiFi dongle.

Change-Id: I057a27034a923310e7b8665d66b224af08958273
Reviewed-on: https://gerrit.chromium.org/gerrit/50014
Reviewed-by: Elly Jones <ellyjones@chromium.org>
Commit-Queue: Paul Stewart <pstew@chromium.org>
Tested-by: Paul Stewart <pstew@chromium.org>

diff --git a/crosh/crosh-dev b/crosh/crosh-dev
--- a/crosh/crosh-dev
+++ b/crosh/crosh-dev
@@ -10,6 +10,16 @@ if [ "$(basename $0)" = "crosh-dev" ]; then
 fi
 
 DEV_HELP='
+ packet_capture [ --device <device> ] [ --frequency <frequency> ] "
+                [ --ht-location <above|below> ] "
+                [ --monitor-connection-on <monitored_device> ]"
+  Start packet capture.  Start a device-based capture on <device>,
+  or do an over-the-air capture on <frequency> with an optionally
+  provided HT channel location.  An over-the-air capture can also
+  be initiated using the channel parameters of a currently connected
+  <monitored_device>.  Note that over-the-air captures are not available
+  with all 802.11 devices.
+
  shell
   Open a command line shell.
 
@@ -24,6 +34,56 @@ DEV_HELP='
 '
 
 HELP="$HELP$DEV_HELP"
+
+cmd_packet_capture() {
+  local option="dict:string:variant:"
+
+  # NB: use printf to avoid echo interpreting -n
+  while [ "$(printf '%s' "$1" | cut -c1)" = "-" ]; do
+    # Do just enough parsing to filter/map options; we
+    # depend on debugd and capture_utility to handle final validation
+    if [ "$1" = "--device" ]; then
+      shift; option="${option}device,string:$1,"
+    elif [ "$1" = "--frequency" ]; then
+      shift; option="${option}frequency,int32:$1,"
+    elif [ "$1" = "--ht-location" ]; then
+      shift; option="${option}ht_location,string:$1,"
+    elif [ "$1" = "--monitor-connection-on" ]; then
+      shift; option="${option}monitor_connection_on,string:$1,"
+    else
+      echo "Unknown option: $1"
+      return 1
+    fi
+
+    shift
+  done
+
+  option=$(echo "$option" | sed 's/,$//')
+
+  local downloads_dir="/home/${USER}/user/Downloads"
+  if ! capture_file=$(mktemp ${downloads_dir}/packet_capture_XXXX.pcap); then
+    echo "Couldn't create capture file."
+    return 1
+  fi
+  local fifo="$(mk_fifo)"
+  debugd PacketCaptureStart "fd:1" "fd:3" "$option" \
+      2>&1 > "$fifo" 3>${capture_file} &
+  read pid < "$fifo"
+  echo "pid: $pid"
+  (while read line; do echo "$line"; done) < "$fifo"
+  debugd PacketCaptureStop "string:$pid"
+  if [ $? -ne 0 ]; then
+    echo "Can't stop packet capture"
+    return 1
+  fi
+  rm -rf "$(dirname ${fifo})"
+  if [ -s "${capture_file}" ]; then
+    echo "Capture stored in ${capture_file}"
+  else
+    echo "No packets captured!"
+    rm -f "${capture_file}"
+  fi
+}
 
 cmd_shell() {
  local shell="/bin/sh"
