crosh: added enrollment status crosh command
Added enterprise enrollment crosh command
enroll_status [--mode] [--domain] [--user]

BUG=chromium:547310
TEST=ran cmd in test VM - enterprise enrolled and non enrolled

Change-Id: I578a71907f3b209a0a494ce5fdfbbb86afe06dca
Reviewed-on: https://chromium-review.googlesource.com/308661
Commit-Ready: Yehuda Yefet <yyefetnyc@gmail.com>
Tested-by: Yehuda Yefet <yyefet@google.com>
Tested-by: Yehuda Yefet <yyefetnyc@gmail.com>
Reviewed-by: Yehuda Yefet <yyefet@google.com>
Reviewed-by: Alex Deymo <deymo@chromium.org>
Reviewed-by: Yehuda Yefet <yyefetnyc@gmail.com>

diff --git a/crosh/crosh b/crosh/crosh
--- a/crosh/crosh
+++ b/crosh/crosh
@@ -1193,6 +1193,70 @@ cmd_dump_emk() (
                        --name=attest-ent-machine
 )
 
+USAGE_enroll_status='[--mode] [--domain] [--user]'
+HELP_enroll_status='
+  Displays device enrollment information.
+'
+cmd_enroll_status() (
+  if [ "$1" = "" ]; then
+    if check_enterprise_mode; then
+      echo "Enrollment mode:"
+      /usr/sbin/cryptohome --action=install_attributes_get \
+        --name=enterprise.mode
+    else
+      echo "This device is not enterprise enrolled."
+    fi
+  fi
+
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      "--mode")
+        if check_enterprise_mode; then
+          echo "Enrollment mode:"
+          /usr/sbin/cryptohome --action=install_attributes_get \
+            --name=enterprise.mode
+        else
+          echo "This device is not enterprise enrolled."
+        fi
+        ;;
+
+      "--domain")
+        if check_enterprise_mode; then
+          echo "Enrollment domain:"
+          /usr/sbin/cryptohome --action=install_attributes_get \
+            --name=enterprise.domain
+        else
+          echo "Enterprise enrollment domain not found."
+        fi
+        ;;
+
+      "--user")
+        if check_enterprise_mode; then
+          echo "Enrollment user:"
+          /usr/sbin/cryptohome --action=install_attributes_get \
+            --name=enterprise.user
+        else
+          echo "Enterprise enrollment user not found."
+        fi
+        ;;
+
+      *)
+        help "unknown option: $1"
+        return 1
+        ;;
+    esac
+
+    shift
+  done
+)
+
+check_enterprise_mode() {
+  if ! /usr/sbin/cryptohome --action=install_attributes_get \
+      --name=enterprise.mode 2>&1 | grep -q "enterprise"; then
+    return 1
+  fi
+}
+
 USAGE_tpm_status=''
 HELP_tpm_status='
   Prints TPM (Trusted Platform Module) status information.
