crosh: network_diag: validate hostnames/IPs
If you typo an address to probe, you get a stream of resolution errors
if it's an invalid DNS name.  Do some sanity checking up front so the
user knows what's going on vs getting even more confused.

BUG=chromium:766271
TEST=`network_diag 127.0.0.1;` throws a nice error now

Change-Id: Iee02f197748187441de452dd806bba991d945fcf
Reviewed-on: https://chromium-review.googlesource.com/671878
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mattias Nissler <mnissler@chromium.org>
Reviewed-by: Brian Norris <briannorris@chromium.org>

diff --git a/crosh/network_diag b/crosh/network_diag
--- a/crosh/network_diag
+++ b/crosh/network_diag
@@ -1105,6 +1105,17 @@ diag_gateway_latency () {
   fi
 }
 
+valid_host () {
+  local host="$1"
+
+  # Allow things that look like valid IPv4/IPv6/DNS.  This doesn't deal with
+  # fully validating the forms, just reject grossly invalid ones.  We'll still
+  # rely on the network to do the final resolution.
+  # Note: This probably doesn't support IDN, so people will have to handle the
+  # punycode transformations themselves.
+  echo "${host}" | grep -q -E '^[-A-Za-z0-9.:]+$'
+}
+
 usage () {
   echo "Usage: $0 [--date|--flimflam|--link|--show-macs|--wifi|--help|"
   echo "           --wifi-mon] [host]"
@@ -1178,6 +1189,10 @@ main () {
         option=${rest[0]}
       else
         test_host=${rest[0]}
+        if ! valid_host "${test_host}"; then
+          echo "Invalid host: ${test_host}"
+          exit 1
+        fi
         diag_run "${test_host}" "${proxy}"
         return
       fi
@@ -1185,6 +1200,10 @@ main () {
     2)
       option=${rest[0]}
       test_host=${rest[1]}
+      if ! valid_host "${test_host}"; then
+        echo "Invalid host: ${test_host}"
+        exit 1
+      fi
       option_and_arg_provided=yes
       ;;
     *)
