power_manager: metrics: Add bitfix metrics
We'd like to collect how many bitfixes happened across a suspend
resume, so add two metrics:
- Power.BitfixChunks: Number of chunks fixed
- Power.BitfixFixes: Number of words fixed

This also slightly optimizes some of the greps in this file by
splitting out the most recent resume only.

BUG=chrome-os-partner:16149
TEST=Run suspend_stress_test.  After seeing some errors check
chrome://histograms and see bitfix counts.  Match against
/var/log/messages
TEST=On x86 chromebook go through a few suspend/resume cycles
and see that Power.KernelResumeTimeOnXXX gets samples.

Change-Id: Iea2c8da163fd3f9733cff845d3a8fba9ab39b83b
Reviewed-on: https://gerrit.chromium.org/gerrit/37951
Tested-by: Doug Anderson <dianders@chromium.org>
Reviewed-by: Daniel Erat <derat@chromium.org>
Reviewed-by: Jon Kliegman <kliegs@chromium.org>
Commit-Ready: Doug Anderson <dianders@chromium.org>

diff --git a/power_manager/scripts/send_metrics_on_resume b/power_manager/scripts/send_metrics_on_resume
--- a/power_manager/scripts/send_metrics_on_resume
+++ b/power_manager/scripts/send_metrics_on_resume
@@ -19,6 +19,33 @@ log_msg() {
     logger -t "send_metrics_on_resume[${PPID}]" $@
 }
 
+# Creates a file based on /var/log/messages containing messages from the most
+# recent resume onwards.  This speeds up greps and also makes it possible
+# to extract counts (like bitfix) from the most recent resume.
+#
+# Prints the name of the temp file created.
+split_recent_messages() {
+  local suspend_start="Going to suspend-to-RAM state"
+  local count=$(grep -c "$suspend_start" /var/log/messages)
+  local tempdir=$(mktemp --tmpdir -d send_metrics_on_resume.XXXXXXXXXX)
+
+  csplit -s -f $tempdir/recent_messages /var/log/messages \
+    "%$suspend_start%" {$((count-1))}
+
+  echo "$tempdir/recent_messages00"
+}
+
+# Cleanup files created by split_recent_messages
+# Arguments:
+#   $1 - Result returned by split_recent_messages()
+cleanup_recent_messages() {
+  [ -n "$1" ] || return
+  local recent_messages="$1"
+
+  /bin/rm "$recent_messages"
+  /bin/rmdir $(dirname "$recent_messages")
+}
+
 # Sends to UMA the total time since going in suspend:
 #   Power.TimeInSuspendAtBoot
 #   Power.TimeInSuspendAtResume
@@ -62,20 +89,25 @@ calculate_firmware_resume_time() {
 }
 
 # Prints the timestamp of the last occurrence of a specified string in
-# /var/log/messages, or nothing otherwise.
+# the recent messages, or nothing otherwise.
 # Arguments:
 #   $1 - string to look for
+#   $2 - Path to messages for most recent resume onward.
 get_last_message_timestamp() {
-  [ -n "$1" ] || return
-  /bin/grep -F "$1" /var/log/messages \
+  [ -n "$1" -a -n "$2" ] || return
+  /bin/grep -F "$1" "$2" \
     | /usr/bin/tail -n1 \
     | /bin/sed 's/.*\[\s*\([0-9.]*\)].*/\1/'
 }
 
 # Find a message related to the start of suspend and parse out its timestamp. It
 # returns the time stamp of the message it found or nothing.
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
 get_start_suspend_time() {
-  timestamp=$(get_last_message_timestamp "Freezing user space")
+  [ -n "$1" ] || return
+
+  timestamp=$(get_last_message_timestamp "Freezing user space" "$1")
   [ -n "$timestamp" ] && echo "$timestamp"
 }
 
@@ -83,20 +115,27 @@ get_start_suspend_time() {
 # timestamp. Since there are multiple possible messages, this function searches
 # for each one in order. It returns the time stamp of the message it found or
 # nothing.
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
 get_end_suspend_time() {
-  local timestamp=$(get_last_message_timestamp "Back to C!")
+  [ -n "$1" ] || return
+
+  local timestamp=$(get_last_message_timestamp "Back to C!" "$1")
   [ -z "$timestamp" ] &&
-    timestamp=$(get_last_message_timestamp "Low-level resume complete")
+    timestamp=$(get_last_message_timestamp "Low-level resume complete" "$1")
   [ -z "$timestamp" ] &&
-    timestamp=$(get_last_message_timestamp "Entering suspend state")
+    timestamp=$(get_last_message_timestamp "Entering suspend state" "$1")
   echo "$timestamp"
 }
 
 # Find a message related to the end of resume and parse out its timestamp. Since
 # there are multiple possible messages, this function searches for each one in
 # order.
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
 get_end_resume_time() {
-  timestamp=$(get_last_message_timestamp "Restarting tasks")
+  [ -n "$1" ] || return
+  timestamp=$(get_last_message_timestamp "Restarting tasks" "$1")
   echo "$timestamp"
 }
 
@@ -107,15 +146,20 @@ get_end_resume_time() {
 #   Power.KernelSuspendTimeOnBattery
 #   Power.FirmwareResumeTimeOnAC
 #   Power.FirmwareResumeTimeOnBattery
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
 send_suspend_resume_time() {
+  [ -n "$1" ] || return
+  local recent_messages="$1"
+
   # On suspend, powerd_suspend stores the power status to a file.
   local power_status_on_suspend=/var/log/metrics/power-status-on-suspend
   [ -r $power_status_on_suspend ] || return
 
   # Greps the timestamps.
-  local start_suspend_time=$(get_start_suspend_time)
-  local end_suspend_time=$(get_end_suspend_time)
-  local end_resume_time=$(get_end_resume_time)
+  local start_suspend_time=$(get_start_suspend_time "$recent_messages")
+  local end_suspend_time=$(get_end_suspend_time "$recent_messages")
+  local end_resume_time=$(get_end_resume_time "$recent_messages")
 
   [ -z "$start_suspend_time" ] && log_msg "Unable to get start_suspend_time"
   [ -z "$end_suspend_time" ] && log_msg "Unable to get end_suspend_time"
@@ -147,11 +191,53 @@ send_suspend_resume_time() {
   /bin/rm -f $power_status_on_suspend
 }
 
+# Find the number of bitfixed chunks
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
+get_bitfix_chunks() {
+  [ -n "$1" ] || return
+  grep -c 'bitfix_recover_chunk: Attempting recovery' "$1"
+}
+
+# Find the total number of actual fixes
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
+get_bitfix_fixes() {
+  [ -n "$1" ] || return
+  grep -c '\.\.\.fixed 0x[0-9a-f]* from 0x[0-9a-f]* to 0x[0-9a-f]*' "$1"
+}
+
+# Sends to UMA stats about bitfixes on the most recent suspend/resume:
+#   Power.BitfixChunks - Number of 8K chunks fixed
+#   Power.BitfixFixes - Number of words fixed
+# Arguments:
+#   $1 - Path to messages for most recent resume onward.
+send_bitfix_metrics() {
+  [ -n "$1" ] || return
+  local recent_messages="$1"
+  local enable_file="/sys/module/bitfix_snow/parameters/bitfix_enabled"
+
+  # Get information about bitfix and send it on.
+  if [ "$(cat $enable_file 2>/dev/null)" = "Y" ]; then
+    local bitfix_chunks=$(get_bitfix_chunks "$recent_messages")
+    local bitfix_fixes=$(get_bitfix_fixes "$recent_messages")
+    /usr/bin/metrics_client -e Power.BitfixChunks "$bitfix_chunks" 100 &
+    /usr/bin/metrics_client -e Power.BitfixFixes "$bitfix_fixes" 500 &
+  fi
+}
+
 main() {
   local event="Resume"
   [ "$1" = "-b" ] && event="Boot"
   send_time_in_suspend $event
-  [ $event = "Resume" ] && send_suspend_resume_time
+  if [ $event = "Resume" ]; then
+    local recent_messages=$(split_recent_messages)
+
+    send_suspend_resume_time "$recent_messages"
+    send_bitfix_metrics "$recent_messages"
+
+    cleanup_recent_messages "$recent_messages"
+  fi
 }
 
 main $@
