installer: Keep chromeos-saferemove from exiting with 1 under normal operation
It is possible that chromeos-saferemove exit with 1 if the calling user
does not have permissions on the parent directory of the last directory
in `SAFE_REMOVE_PATHS` -- in this case, the data has already been
removed, but the script will report an error because the directory node
itself could not be removed.

BUG=chromium:856763
TEST=0 exit code when running with undeletable directory

Change-Id: I9f9a5ae2d2d4d1075d507924aefc60db902a29ba
Reviewed-on: https://chromium-review.googlesource.com/1125096
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Tudor Brindus <tbrindus@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/installer/chromeos-saferemove b/installer/chromeos-saferemove
--- a/installer/chromeos-saferemove
+++ b/installer/chromeos-saferemove
@@ -12,10 +12,17 @@ for path in "${SAFE_REMOVE_PATHS}"; do
   # If the path exists and is a symlink, then it should be ignored.
   if [ -e "${path}" -a ! -L "${path}" ]; then
     # Recursively delete all files in the path. Note that we do not follow or
-    # consider any symlinks.
+    # consider any symlinks. Note that secure_erase_file is currently a no-op
+    # for non-eMMC (NVMe) disks, and will do nothing to the data.
     find "${path}" -type f -exec secure_erase_file {} \;
 
-    # Delete the path, since its contents have already been destroyed.
-    rm -rf "${path}"
+    # Delete the path, since its contents have already been destroyed. This
+    # command might fail if we don't have permissions on the *parent* directory,
+    # in which case we should not let the exit code of this script be 1 since
+    # the data within the path has already been removed. In the case that
+    # secure_erase_file fails to remove NVMe contents, rm will still recursively
+    # delete all it can before it tries (and potentially fails) to delete the
+    # top-level directory.
+    rm -rf "${path}" || true
   fi
 done
