Bypass removable check for /dev/mmcblk1
Workaround kernel bug that implements "removable"
in arm mmc reader inconsistantly with the rest of kernel.

BUG=chromium-os:14871
TEST=build, install from sdcard

Change-Id: I2183ad6e4769b59207ba2a50f6c89302e36ee558
Reviewed-on: http://gerrit.chromium.org/gerrit/1877
Reviewed-by: Nick Sanders <nsanders@chromium.org>
Tested-by: Nick Sanders <nsanders@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -130,8 +130,12 @@ elif [ -z "$FLAGS_payload_image" ]; then
 
   if [ "$FLAGS_skip_src_removable" -eq "${FLAGS_FALSE}" ]; then
     if [ "$(cat /sys/block/${SRC#/dev/}/removable)" != "1" ]; then
-      echo "Error: Source does not look like a removable device: $SRC"
-      exit 1
+      # Work around ARM kernel bug http://crosbug.com/14871
+      # Removable flag is implemented inconsistantly for ARM sdcard reader.
+      if [ "${SRC}" != "/dev/mmcblk1" ]; then
+        echo "Error: Source does not look like a removable device: $SRC"
+        exit 1
+      fi
     fi
   fi
 else
