FW Install: Never err
Firmware install happens after we mark the new drive bootable, and
thus it can never fail. If you need to do checks to fail, do those
checks before marking the new drive bootable.

This CL makes firmware update never fail, but log if it wanted to
fail.

BUG=7872
TEST=none

Change-Id: Ie61540109fcb3658d720851de41cebfbdb47073b

Review URL: http://codereview.chromium.org/3775012

diff --git a/installer/chromeos-postinst b/installer/chromeos-postinst
--- a/installer/chromeos-postinst
+++ b/installer/chromeos-postinst
@@ -311,11 +311,19 @@ Partition ${NEW_PART_NUM}, Slot ${BOOT_SLOT}"
       FIRMWARE_UPDATE_ARGS=" $FIRMWARE_UPDATE_MODE "
       echo "Updating firmware ($FIRMWARE_UPDATE_ARGS)"
       env INSTALL_ROOT="${INSTALL_ROOT}" \
-        "${FIRMWARE_UPDATE_SCRIPT}" ${FIRMWARE_UPDATE_ARGS} || exit 1
+        "${FIRMWARE_UPDATE_SCRIPT}" ${FIRMWARE_UPDATE_ARGS}
       # Next step after postinst may take a lot of time (eg, disk wiping)
       # and people may confuse that as 'firmware update takes a long wait',
       # we explicitly prompt here.
-      echo "Firmware update complete."
+      if [ "$?" -eq 0 ]; then
+        echo "Firmware update complete."
+      else
+        echo "Firmware update failed."
+        if [ -n "${IS_FACTORY_INSTALL}" ];
+          echo "Aborting on firmware update failure during factory install"
+          exit 1
+        fi
+      fi
     fi
   fi
 else
