installer: clean up style to use a main func for chromeos-install.
No real functional changes here.  Tidying up to make the future improvements
easier.

BUG=none
TEST=manual: chromeos-install # success.

Change-Id: I5349c1a160fc385439ec6f34f1be377f992ce13e
Reviewed-on: https://chromium-review.googlesource.com/268984
Tested-by: Hung-Te Lin <hungte@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Hung-Te Lin <hungte@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -14,6 +14,20 @@ fi
 . /usr/share/misc/chromeos-common.sh || exit 1
 . /usr/share/misc/shflags || exit 1
 
+# Helpful constants.
+HARDWARE_DIAGNOSTICS_PATH=/tmp/hardware_diagnostics.log
+TMPMNT=/tmp/install-mount-point
+STATEFUL_PART=1
+# This is defined later once we have mounted the ROOT.
+STATEFUL_FORMAT=
+
+# Partition numbers that have assumptions about them. This list should be kept
+# to a minimal. Check copy_partition for most special casing.
+KERNEL_A_PART=2
+ROOTFS_A_PART=3
+KERNEL_B_PART=4
+ROOTFS_B_PART=5
+
 # TODO(installer): Clean up all these flags. There are way too many flags in
 # this script.
 
@@ -54,41 +68,39 @@ preserved"
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
-# Be aggressive.
-set -eu
-
-SUB_CMD_DEBUG_FLAG=""
-if [ "$FLAGS_debug" -eq "${FLAGS_TRUE}" ]; then
-  set -x
-  SUB_CMD_DEBUG_FLAG="--debug"
-fi
+die() {
+  echo "$*" >&2
+  exit 1
+}
 
 # Determine our architecture
-if [ -z "$FLAGS_arch" ]; then
+get_architecture() {
+  if [ -n "${FLAGS_arch}" ]; then
+    case ${FLAGS_arch} in
+    INTEL|ARM|MIPS)
+      echo "${FLAGS_arch}"
+      return 0
+      ;;
+    *)
+      die "Error: Unknown architecture '${FLAGS_arch}'."
+    esac
+  fi
+
   case $(uname -m) in
   i?86|x86_64)
-    ARCH="INTEL"
+    echo "INTEL"
     ;;
   arm*|aarch64)
-    ARCH="ARM"
+    echo "ARM"
     ;;
   mips*)
-    ARCH="MIPS"
+    echo "MIPS"
     ;;
   *)
-    echo "Error: Failed to auto detect architecture" >&2
-    exit 1
+    die "Error: Failed to auto detect architecture."
   esac
-else
-  case ${FLAGS_arch} in
-  INTEL|ARM|MIPS)
-    ;;
-  *)
-    echo "Error: Unknown architecture '$FLAGS_arch'." >& 2
-    exit 1
-  esac
-  ARCH="$FLAGS_arch"
-fi
+  return 0
+}
 
 fast_dd() {
   # Usage: fast_dd <block size> <count> <seek> <skip> other dd args
@@ -257,44 +269,36 @@ get_root_device() {
 }
 
 # Check for optional payload image
-if [ "$FLAGS_skip_rootfs" -eq "$FLAGS_TRUE" -a -s "$FLAGS_gpt_layout" ]; then
-  # Usually this is used for partition setup.
-  SRC=""
-  ROOT=""
-elif [ -z "$FLAGS_payload_image" ]; then
-  # Find root partition of the root block device
-  SRC=$(get_block_dev_from_partition_dev $(get_root_device))
-  ROOT=""
+check_payload_image() {
+  if [ "${FLAGS_skip_rootfs}" -eq "${FLAGS_TRUE}" -a \
+       -s "${FLAGS_gpt_layout}" ]; then
+    # Usually this is used for partition setup.
+    SRC=""
+    ROOT=""
+  elif [ -z "${FLAGS_payload_image}" ]; then
+    # Find root partition of the root block device
+    SRC=$(get_block_dev_from_partition_dev $(get_root_device))
+    ROOT=""
 
-  if [ "$FLAGS_skip_src_removable" -eq "${FLAGS_FALSE}" ]; then
-    if [ "$(cat /sys/block/${SRC#/dev/}/removable)" != "1" ]; then
-      # Work around ARM kernel bug http://crosbug.com/14871
-      # Removable flag is implemented inconsistantly for ARM sdcard reader.
-      if [ "${SRC}" != "/dev/mmcblk1" ]; then
-        echo "Error: Source does not look like a removable device: $SRC"
-        exit 1
+    if [ "${FLAGS_skip_src_removable}" -eq "${FLAGS_FALSE}" ]; then
+      if [ "$(cat /sys/block/${SRC#/dev/}/removable)" != "1" ]; then
+        # Work around ARM kernel bug http://crosbug.com/14871
+        # Removable flag is implemented inconsistantly for ARM sdcard reader.
+        if [ "${SRC}" != "/dev/mmcblk1" ]; then
+          die "Error: Source does not look like a removable device: ${SRC}"
+        fi
       fi
     fi
+  else
+    if [ ! -e "${FLAGS_payload_image}" ]; then
+      die "Error: No payload image found at ${FLAGS_payload_image}"
+    fi
+
+    # Needed to copy PMBR code off image
+    SRC="${FLAGS_payload_image}"
+    ROOT="$(mktemp -d)"
   fi
-else
-  if [ ! -e "$FLAGS_payload_image" ]; then
-    echo "Error: No payload image found at $FLAGS_payload_image"
-    exit 1
-  fi
-
-  # Needed to copy PMBR code off image
-  SRC="$FLAGS_payload_image"
-  ROOT="$(mktemp -d)"
-fi
-
-##############################################################################
-# Helpful constants and functions.
-
-# Where to store any related hardware diagnostics data.
-HARDWARE_DIAGNOSTICS_PATH=/tmp/hardware_diagnostics.log
-PMBRCODE=/tmp/gptmbr.bin
-TMPMNT=/tmp/install-mount-point
-mkdir -p ${TMPMNT}
+}
 
 # Clean any mounts that might be present to avoid
 # aliasing access to block devices.
@@ -342,8 +346,7 @@ loop_offset_setup() {
 
   LOOP_DEV=$(losetup -f --show -o $(($offset * 512)) ${filename})
   if [ -z "$LOOP_DEV" ]; then
-    echo "No free loop device. Free up a loop device or reboot. Exiting."
-    exit 1
+    die "No free loop device. Free up a loop device or reboot. Exiting."
   fi
 
   LOOPS="${LOOP_DEV}${LOOPS:+ }${LOOPS:-}"
@@ -443,19 +446,13 @@ check_removable() {
   local removable
 
   if ! removable=$(cat /sys/block/${DST#/dev/}/removable); then
-    echo "Error: Invalid destination device (must be whole device): ${DST}"
-    exit 1
+    die "Error: Invalid destination device (must be whole device): ${DST}"
   fi
 
   if [ "${removable}" != "0" ]; then
-    echo "Error: Attempt to install to a removeable device: $DST"
-    exit 1
+    die "Error: Attempt to install to a removeable device: ${DST}"
   fi
 }
-
-STATEFUL_PART=1
-# This is defined later once we have mounted the ROOT.
-STATEFUL_FORMAT=
 
 # Wipes and expands the stateful partition.
 wipe_stateful() {
@@ -607,13 +604,6 @@ install_stateful() {
   esac
 }
 
-# Partition numbers that have assumptions about them. This list should be kept
-# to a minimal. Check copy_partition for most special casing.
-KERNEL_A_PART=2
-ROOTFS_A_PART=3
-KERNEL_B_PART=4
-ROOTFS_B_PART=5
-
 # Copy partition from src to dst (figures out partition offsets). Note, this
 # has some special casing for rootfs, kernel, and stateful partitions. In
 # addition, it only copies partitions that are equally sized over one another.
@@ -689,179 +679,205 @@ recreate_nand_partitions() {
   rm -f "${gpt_file}"
 }
 
-##############################################################################
-
-# Start main logic. As little code as possible should go in here. Please make
-# sure put any helper methods above this point to make this main component as
-# simple as possible.
-
-# We untrap on success and run cleanup ourselves. Othewise, on any failure, run
-# our custom trap method to gather any diagnostic data before cleaning up.
-trap cleanup_on_failure EXIT
-
-# Clean media browser mounts if they've popped up.
-prepare_disk
-
-locate_gpt
-
-# Special handling for payload_image. This is passed in for recovery images
-# and usb installs. This is done first so we can read the gpt partition
-# file below.
-if [ -n "${FLAGS_payload_image}" ]; then
-  SRC="${FLAGS_payload_image}"
-  # Mount files that are required to be referenced (when not already mounted).
-  loop_offset_setup "${SRC}" $(partoffset "${SRC}" ${ROOTFS_A_PART})
-  tracked_mount -o ro "${LOOP_DEV}" "${ROOT}"
-  loop_offset_setup "${SRC}" $(partoffset "${SRC}" ${STATEFUL_PART})
-  tracked_mount -o ro "${LOOP_DEV}" "${ROOT}"/mnt/stateful_partition
-fi
-
-# Load the GPT helper functions and the image settings.
-. "${ROOT}/usr/sbin/write_gpt.sh"
-load_base_vars
-
-# Now that we have loaded the partition table we can actually read the format
-# and partition information.
-STATEFUL_FORMAT=$(get_format ${STATEFUL_PART})
-
 # Find our destination device.
 # If the user hasn't selected a destination,
 # we expect that the disk layout declares it for us.
-DST=${FLAGS_dst:-$(get_fixed_dst_drive)}
-if [ -z "${DST}" ]; then
-  echo "Error: can not determine destination device. Specify --dst yourself."
-  exit 1
-fi
-
-if [ "${DST}" = "/dev/mtd0" ]; then
-  FLAGS_mtd_layout=${FLAGS_TRUE}
-fi
-
-# Check out the dst device.
-if [ ${FLAGS_mtd_layout} -eq ${FLAGS_TRUE} ]; then
-  FLAGS_skip_dst_removable=${FLAGS_TRUE}
-elif [ ! -b "${DST}" ]; then
-  echo "Error: Unable to find destination block device: ${DST}"
-  exit 1
-fi
-
-check_removable
-
-if [ "$DST" = "$SRC" ]; then
-  echo "Error: src and dst are the same: $SRC = $DST"
-  exit 1
-fi
-
-# Ask for confirmation to be sure.
-echo "This will install from '$SRC' to '$DST'."
-echo "This will erase all data at this destination: $DST"
-if [ ${FLAGS_yes} -eq ${FLAGS_FALSE} ]; then
-  read -p "Are you sure (y/N)? " SURE
-  if [ "$SURE" != "y" ]; then
-    echo "Ok, better safe than sorry; you answered '$SURE'."
-    # Don't run diagnostics if the user explictly bailed out.
-    trap - EXIT
-    cleanup
-    exit 1
+check_dst() {
+  if [ -z "${DST}" ]; then
+    die "Error: can not determine destination device. Specify --dst yourself."
   fi
-fi
 
-if [ -n "${FLAGS_pmbr_code}" ]; then
-  PMBRCODE="${FLAGS_pmbr_code}"
-elif [ ${FLAGS_mtd_layout} -eq ${FLAGS_TRUE} ]; then
-  # We don't use PMBR if this is on MTD.
-  dd bs=512 count=1 if=/dev/zero of="${PMBRCODE}"
-elif [ "$ARCH" = "ARM" ]; then
-  # Store the existing PMBR from the destination in the temp pmbr file so we can
-  # restore it when we're installing the GPT. This ensures that we preserve
-  # settings set by crossystem (such as dev_boot_usb).
-  dd bs=512 count=1 if=$DST of=$PMBRCODE
-else
-  # Steal the PMBR code from the source MBR to put on the dest MBR, for booting
-  # on legacy-BIOS devices.
-  dd bs=512 count=1 if=$SRC of=$PMBRCODE
-fi
+  if [ "${DST}" = "/dev/mtd0" ]; then
+    FLAGS_mtd_layout=${FLAGS_TRUE}
+  fi
 
-# Write the GPT using the board specific script. The parameters are ignored
-# on MTD devices.
-write_base_table "${DST}" "${PMBRCODE}"
-legacy_offset_size_export "${DST}"
-
-if [ ${FLAGS_mtd_layout} -eq ${FLAGS_FALSE} ]; then
-  # Reload the partition table on block devices only.
-  # On MTD, the ChromeOS kernel loads the partition table at boot time.
-  #
-  # In some cases, we may be racing with udev for access to the
-  # device leading to EBUSY when we reread the partition table.  We
-  # avoid the conflict by using `udevadm settle`, so that udev goes
-  # first.  cf. crbug.com/343681.
-  udevadm settle
-  /sbin/blockdev --rereadpt ${DST}
-else
-  # On NAND, we need to recreate the partition table.
-  recreate_nand_partitions "${DST}"
-fi
-
-if [ ${FLAGS_skip_rootfs} -eq ${FLAGS_TRUE} ]; then
-  echo Done installing partitons.
-  exit 0
-fi
-
-if [ ${FLAGS_preserve_stateful} -eq ${FLAGS_FALSE} -a \
-     ! -n "${FLAGS_lab_preserve_logs}" ]; then
-  wipe_stateful
-fi
-
-# Install the content. Do so in reverse order to have stateful get installed
-# last. The order shouldn't matter but legacy behavior has us go in reverse
-# order.
-for CURRENT_PART in $(seq 12 -1 1); do
-  copy_partition ${CURRENT_PART} ${SRC} ${DST}
-done
-
-
-################################################################################
-# Post partition copying work and special casing
-################################################################################
-
-POSTINST_BIOS_ARGS=""
-if [ -n "${FLAGS_target_bios}" ]; then
-  POSTINST_BIOS_ARGS="--bios ${FLAGS_target_bios}"
-fi
-
-# Now run the postinstall script on one new rootfs. Note that even though
-# we're passing the new destination partition number as an arg, the postinst
-# script had better not try to access it, for the reasons we just gave.
-# We can't run this if the target arch isn't the same as the host arch
-if [ "${FLAGS_skip_postinstall}" -eq "${FLAGS_FALSE}" ]; then
+  # Check out the dst device.
   if [ ${FLAGS_mtd_layout} -eq ${FLAGS_TRUE} ]; then
-    if ! [ -b "/dev/ubiblock${ROOTFS_A_PART}_0" ]; then
-      ubiblock -c "/dev/ubi${ROOTFS_A_PART}_0"
-    fi
-    LOOP_DEV="/dev/ubiblock${ROOTFS_A_PART}_0"
-    # We need to pass the __writable__ device to postinst, hence ubiX_0.
-    DST_ROOTFS_DEV="/dev/ubi${ROOTFS_A_PART}_0"
+    FLAGS_skip_dst_removable=${FLAGS_TRUE}
+  elif [ ! -b "${DST}" ]; then
+    die "Error: Unable to find destination block device: ${DST}"
+  fi
+
+  if [ "${DST}" = "${SRC}" ]; then
+    die "Error: src and dst are the same: ${SRC} = ${DST}"
+  fi
+}
+
+# Gets the right PMBR (protective master boot record) code (either from
+# FLAGS_pmbr_code, source or destination media) by printing the file path
+# containing PMBR code in standard out.
+get_pmbr_code() {
+  local pmbr_code="/tmp/gptmbr.bin"
+
+  if [ -n "${FLAGS_pmbr_code}" ]; then
+    echo "${FLAGS_pmbr_code}"
+  elif [ ${FLAGS_mtd_layout} -eq ${FLAGS_TRUE} ]; then
+    # We don't use PMBR if this is on MTD.
+    dd bs=512 count=1 if=/dev/zero of="${pmbr_code}" >/dev/null 2>&1
+    echo "${pmbr_code}"
+  elif [ "${ARCH}" = "ARM" ]; then
+    # Store the existing PMBR from the destination in the temp pmbr file so we
+    # can restore it when we're installing the GPT. This ensures that we
+    # preserve settings set by crossystem (such as dev_boot_usb).
+    dd bs=512 count=1 if="${DST}" of="${pmbr_code}" >/dev/null 2>&1
+    echo "${pmbr_code}"
   else
-    loop_offset_setup ${DST} ${START_ROOTFS_A}
-    DST_ROOTFS_DEV=$(make_partition_dev ${DST} ${ROOTFS_A_PART})
+    # Steal the PMBR code from the source MBR to put on the dest MBR, for
+    # booting on legacy-BIOS devices.
+    dd bs=512 count=1 if="${SRC}" of="${pmbr_code}" >/dev/null 2>&1
+    echo "${pmbr_code}"
   fi
+}
 
-  mount_on_loop_dev
-  IS_INSTALL="1" ${TMPMNT}/postinst "${DST_ROOTFS_DEV}" \
-    ${SUB_CMD_DEBUG_FLAG} "${POSTINST_BIOS_ARGS}"
-  umount_from_loop_dev
+# Reload the system partitions after the partition table was modified (so the
+# device nodes like /dev/sda1 can be accessed).
+reload_partitions() {
   if [ ${FLAGS_mtd_layout} -eq ${FLAGS_FALSE} ]; then
-    loop_offset_cleanup
+    # Reload the partition table on block devices only.
+    # On MTD, the ChromeOS kernel loads the partition table at boot time.
+    #
+    # In some cases, we may be racing with udev for access to the
+    # device leading to EBUSY when we reread the partition table.  We
+    # avoid the conflict by using `udevadm settle`, so that udev goes
+    # first.  cf. crbug.com/343681.
+    udevadm settle
+    /sbin/blockdev --rereadpt "${DST}"
+  else
+    # On NAND, we need to recreate the partition table.
+    recreate_nand_partitions "${DST}"
   fi
-fi
+}
 
-# Force data to disk before we declare done.
-sync
+# Post partition copying work and special casing
+do_post_install() {
+  local args=""
+  if [ -n "${FLAGS_target_bios}" ]; then
+    args="${args} --bios ${FLAGS_target_bios}"
+  fi
+  if [ "${FLAGS_debug}" -eq "${FLAGS_TRUE}" ]; then
+    args="${args} --debug"
+  fi
+  local dst_rootfs_dev=""
 
-cleanup
-trap - EXIT
+  # Now run the postinstall script on one new rootfs. Note that even though
+  # we're passing the new destination partition number as an arg, the postinst
+  # script had better not try to access it, for the reasons we just gave.
+  # We can't run this if the target arch isn't the same as the host arch
+  if [ "${FLAGS_skip_postinstall}" -eq "${FLAGS_FALSE}" ]; then
+    if [ ${FLAGS_mtd_layout} -eq ${FLAGS_TRUE} ]; then
+      if ! [ -b "/dev/ubiblock${ROOTFS_A_PART}_0" ]; then
+        ubiblock -c "/dev/ubi${ROOTFS_A_PART}_0"
+      fi
+      LOOP_DEV="/dev/ubiblock${ROOTFS_A_PART}_0"
+      # We need to pass the __writable__ device to postinst, hence ubiX_0.
+      dst_rootfs_dev="/dev/ubi${ROOTFS_A_PART}_0"
+    else
+      loop_offset_setup ${DST} ${START_ROOTFS_A}
+      dst_rootfs_dev=$(make_partition_dev ${DST} ${ROOTFS_A_PART})
+    fi
 
-echo "------------------------------------------------------------"
-echo ""
-echo "Installation to '$DST' complete."
-echo "Please shutdown, remove the USB device, cross your fingers, and reboot."
+    mount_on_loop_dev
+    IS_INSTALL="1" ${TMPMNT}/postinst "${dst_rootfs_dev}" ${args}
+    umount_from_loop_dev
+    if [ ${FLAGS_mtd_layout} -eq ${FLAGS_FALSE} ]; then
+      loop_offset_cleanup
+    fi
+  fi
+}
+
+main() {
+  # Be aggressive.
+  set -eu
+  if [ "${FLAGS_debug}" = "${FLAGS_TRUE}" ]; then
+    set -x
+  fi
+
+  ARCH="$(get_architecture)" || exit $?
+
+  check_payload_image
+  mkdir -p "${TMPMNT}"
+
+  # We untrap on success and run cleanup ourselves. Othewise, on any failure, run
+  # our custom trap method to gather any diagnostic data before cleaning up.
+  trap cleanup_on_failure EXIT
+
+  # Clean media browser mounts if they've popped up.
+  prepare_disk
+  locate_gpt
+
+  # Special handling for payload_image. This is passed in for recovery images
+  # and usb installs. This is done first so we can read the gpt partition
+  # file below.
+  if [ -n "${FLAGS_payload_image}" ]; then
+    SRC="${FLAGS_payload_image}"
+    # Mount files that are required to be referenced (when not already mounted).
+    loop_offset_setup "${SRC}" $(partoffset "${SRC}" ${ROOTFS_A_PART})
+    tracked_mount -o ro "${LOOP_DEV}" "${ROOT}"
+    loop_offset_setup "${SRC}" $(partoffset "${SRC}" ${STATEFUL_PART})
+    tracked_mount -o ro "${LOOP_DEV}" "${ROOT}"/mnt/stateful_partition
+  fi
+
+  # Load the GPT helper functions and the image settings.
+  . "${ROOT}/usr/sbin/write_gpt.sh"
+  load_base_vars
+
+  # Now that we have loaded the partition table we can actually read the format
+  # and partition information.
+  STATEFUL_FORMAT=$(get_format ${STATEFUL_PART})
+
+  DST=${FLAGS_dst:-$(get_fixed_dst_drive)}
+  check_dst
+  check_removable
+
+  # Ask for confirmation to be sure.
+  echo "This will install from '${SRC}' to '${DST}'."
+  echo "This will erase all data at this destination: ${DST}"
+  local sure
+  if [ ${FLAGS_yes} -eq ${FLAGS_FALSE} ]; then
+    read -p "Are you sure (y/N)? " sure
+    if [ "${sure}" != "y" ]; then
+      # Don't run diagnostics if the user explictly bailed out.
+      trap - EXIT
+      cleanup
+      die "Ok, better safe than sorry; you answered '${sure}'."
+    fi
+  fi
+
+  # Write the GPT using the board specific script. The parameters are ignored
+  # on MTD devices.
+  write_base_table "${DST}" "$(get_pmbr_code)"
+  legacy_offset_size_export "${DST}"
+  reload_partitions
+
+  if [ ${FLAGS_skip_rootfs} -eq ${FLAGS_TRUE} ]; then
+    echo Done installing partitons.
+    exit 0
+  fi
+
+  if [ ${FLAGS_preserve_stateful} -eq ${FLAGS_FALSE} -a \
+       ! -n "${FLAGS_lab_preserve_logs}" ]; then
+    wipe_stateful
+  fi
+
+  # Install the content. Do so in reverse order to have stateful get installed
+  # last. The order shouldn't matter but legacy behavior has us go in reverse
+  # order.
+  local current_part
+  for current_part in $(seq 12 -1 1); do
+    copy_partition ${current_part} ${SRC} ${DST}
+  done
+
+  do_post_install
+
+  # Force data to disk before we declare done.
+  sync
+  cleanup
+  trap - EXIT
+
+  echo "------------------------------------------------------------"
+  echo ""
+  echo "Installation to '${DST}' complete."
+  echo "Please shutdown, remove the USB device, cross your fingers, and reboot."
+}
+
+main "$@"
