installer: fix the "umount: XXX not mounted" error message during postinst
When cleaning loop devices, it may be not always mounted.
This CL makes it allowing an extra parameter to specify any additional
steps to be performed before releasing a loop device.

BUG=chromium-os:9278
TEST=Build an USB image with this change, and then /usr/sbin/chromeos-install
 Before: Seeing "umount: /dev/loop2: not mounted" and
                "umount: /dev/loop3: not mounted" in output messages
 After: No error message. Also verified "sudo losetup -a" does not leave
        any resources mounted.

Change-Id: I10dfa08b037bb11bd821754f32a7a39c155fe445

Review URL: http://codereview.chromium.org/5122002

diff --git a/installer/chromeos-setimage b/installer/chromeos-setimage
--- a/installer/chromeos-setimage
+++ b/installer/chromeos-setimage
@@ -113,21 +113,29 @@ ESP_LOOP=
 ROOT_LOOP=
 KERN_LOOP=
 
+# Cleans up a device and unmount if required.
 cleanup_loop() {
   local dev="$1"
-  if [ -z "$dev" ]; then
+  local need_umount="$2"
+  if [ -z "${dev}" ]; then
     return 0
   fi
-  (sudo umount "$dev" || true)
-  (sudo losetup -d "$dev" || true)
+  if [ ${need_umount} -eq ${FLAGS_TRUE} ]; then
+    sudo umount -d "${dev}" || true
+  elif [ ${need_umount} -eq ${FLAGS_FALSE} ]; then
+    sudo losetup -d "${dev}" || true
+  else
+    echo "INTERNAL ERROR: unknown parameter for cleanup_loop: ${need_umount}" >&2
+  fi
 }
 
 cleanup() {
-  cleanup_loop "${ESP_LOOP}"
+  # Currently only ESP may be mounted. KERN and ROOT are never mounted.
+  cleanup_loop "${ESP_LOOP}" "${FLAGS_TRUE}"
   ESP_LOOP=
-  cleanup_loop "${KERN_LOOP}"
+  cleanup_loop "${KERN_LOOP}" "${FLAGS_FALSE}"
   KERN_LOOP=
-  cleanup_loop "${ROOT_LOOP}"
+  cleanup_loop "${ROOT_LOOP}" "${FLAGS_FALSE}"
   ROOT_LOOP=
 
   # Failing to clean this up isn't the worst.
