Installer: support for installing/updating syslinux.
This change was started by Will Drewry.

Allows users running 0.7.42.x and up to autoupdate to the latest
images, which use syslinux as the bootloader.

TEST=tested the following scenarios on the device:
  - 0.7.42.11 -> this CL (via update)
  - 0.7.46.8 -> this CL (via update)
  - this CL -> this CL (via update)
  - direct install of this CL (via USB boot + installer)
BUG=3

Review URL: http://codereview.chromium.org/2924011

diff --git a/installer/chromeos-postinst b/installer/chromeos-postinst
--- a/installer/chromeos-postinst
+++ b/installer/chromeos-postinst
@@ -9,7 +9,7 @@
 # the rootfs should be updated w/ the new bootloader config. If empty, the
 # rootfs is mounted-read only and should not be updated.
 
-# Update /boot/extlinux.conf.
+# Update syslinux configuration file and install syslinux itself.
 INSTALL_ROOT=$(dirname "$0")
 INSTALL_DEV="$1"
 POSTCOMMIT="$2"
@@ -32,6 +32,8 @@ case ${NEW_PART_NUM} in
     exit 1
     ;;
 esac
+# For legacy and efi boot, we only have one boot-capable partition.
+LEGACY_PART_NUM=12
 
 if [ "$POSTCOMMIT" != "--postcommit" ]; then
   # Pre-commit. Returning an error here will prevent ever booting into the
@@ -41,30 +43,56 @@ if [ "$POSTCOMMIT" != "--postcommit" ]; then
   echo " Set boot target to ${INSTALL_DEV}: \
 Partition ${NEW_PART_NUM}, Slot ${BOOT_SLOT}"
 
-  if [ -f "${INSTALL_ROOT}"/boot/extlinux.conf ]; then
-    echo "Updating /boot/extlinux.conf target"
-    # If the mount-point is read-write, update the bootloader
-    # Only update extlinux.conf if $1 is non-empty
-    if [ -n "$INSTALL_DEV" ]; then
-      # Set default label to chromeos-hd.
-      sed -i 's/^DEFAULT .*/DEFAULT chromeos-hd/' \
-          "$INSTALL_ROOT"/boot/extlinux.conf || true
-      sed -i "{ s:HDROOT:$INSTALL_DEV: }" \
-          "$INSTALL_ROOT"/boot/extlinux.conf || true
+  IS_INTEL_ARCH=$(uname -m | grep "^i.86\$" | wc -l)
+  # Install syslinux files on EFI partition
+  if [ -z "${IS_INSTALL}" -a "${IS_INTEL_ARCH}" -eq "1" ]; then
+    EFI_MNT=$(mktemp -d /tmp/EFI.XXXXXX)
+    EFI_PART=$(make_partition_dev "${ROOT_DEV}" "${LEGACY_PART_NUM}")
+    mount "${EFI_PART}" "${EFI_MNT}"
+    set +e
+    cp -R "${INSTALL_ROOT}"/boot/syslinux "${EFI_MNT}"
+    ERR=${?}
+    echo "Updating syslinux"
+    # Set up grub.cfg
+    if [ "${ERR}" -eq "0" ]; then
+      "${INSTALL_ROOT}"/usr/sbin/chromeos-setimage ${BOOT_SLOT} \
+          --dst=${ROOT_DEV} --run_as_root \
+          --update_syslinux_cfg="${EFI_MNT}/syslinux/root.${BOOT_SLOT}.cfg" \
+          --esp_mounted_at="${EFI_MNT}" \
+          --update_vmlinuz=${INSTALL_ROOT}/boot/vmlinuz
+      ERR=${?}
+    fi
+    umount "${EFI_MNT}"
+    rmdir "${EFI_MNT}"
+    if [ "${ERR}" -ne "0" ]; then
+      echo "Failed to copy syslinux files in and make them bootable."
+      exit 1
+    fi
+    set -e
+    mount -o bind /dev "${INSTALL_ROOT}"/dev
+    set +e
+    mount -o bind /proc "${INSTALL_ROOT}"/proc
+    ERR=${?}
+    if [ "${ERR}" -ne "0" ]; then
+      umount "${INSTALL_ROOT}"/dev
+      echo "Failed to bind mount /proc"
+      exit 1
+    fi
+    chroot "${INSTALL_ROOT}" /usr/bin/syslinux "${EFI_PART}"
+    ERR=${?}
+    umount "${INSTALL_ROOT}"/proc
+    umount "${INSTALL_ROOT}"/dev
+    set -e
+    if [ "${ERR}" -ne "0" ]; then
+      echo "Failed to run syslinux on: ${EFI_PART}"
+      exit 1
     fi
   fi
-
-
-  echo "Updating grub target for EFI BIOS"
-  # Set up grub.cfg
-  "${INSTALL_ROOT}"/usr/sbin/chromeos-setimage ${BOOT_SLOT} \
-      --dst=${ROOT_DEV} --run_as_root
 
   # Set up gpt boot selection for legacy devices.
   # flush linux caches; seems to be necessary
   sync
   echo 3 > /proc/sys/vm/drop_caches
-
 
   echo "Updating gpt PMBR target for legacy BIOS"
   # Configure the PMBR to boot the new image.
@@ -74,12 +102,14 @@ Partition ${NEW_PART_NUM}, Slot ${BOOT_SLOT}"
   # with the old image's gpt binaries.
   #
   if [ -x /usr/bin/cgpt ]; then
-    cgpt boot -i $NEW_PART_NUM ${ROOT_DEV} 2>&1
+    echo "marking part $LEGACY_PART_NUM bootable (new)"
+    cgpt boot -i $LEGACY_PART_NUM ${ROOT_DEV} 2>&1
   else
     # The old gpt tool requires a -b arg to specify the PMBR bootcode. We don't
     # want to change the code, so we have to extract it, then put it back.
     dd if=${ROOT_DEV} bs=512 count=1 of=/tmp/oldpmbr.bin
-    gpt -S boot -i $NEW_PART_NUM -b /tmp/oldpmbr.bin ${ROOT_DEV} 2>&1
+    echo "marking part $LEGACY_PART_NUM bootable (old)"
+    gpt -S boot -i $LEGACY_PART_NUM -b /tmp/oldpmbr.bin ${ROOT_DEV} 2>&1
   fi
 
 
@@ -97,5 +127,30 @@ else
   echo -n  # this is a noop, required for 'sh'
 
   # We are deprecating post-commit postinst, so do not put anything in here.
+  
+  echo "Updating gpt PMBR target for legacy BIOS (post-commit)"
+  # I know we aren't supposed to put anything here, but here is the
+  # justification:
+  # The updater in 0.7.42.* sets the rootfs bootable after postinst (precommit)
+  # is run, and then runs postinst (postcommit). Later versions of the updater
+  # neither mark partitions bootable, nor run postinst (postcommit). In those
+  # newer versions, this code won't be run, but it won't need to be run.
+  # If we didn't care about clients as old as 0.7.42.*, we could leave this
+  # area empty. Unfortunately, we can't update old updaters.
+
+  # At some point, when we don't care about clients that old (0.7.42.*),
+  # We should remove this whole code path in this file.
+
+
+  if [ -x /usr/bin/cgpt ]; then
+    echo "marking part $LEGACY_PART_NUM bootable (new)"
+    cgpt boot -i $LEGACY_PART_NUM ${ROOT_DEV} 2>&1
+  else
+    # The old gpt tool requires a -b arg to specify the PMBR bootcode. We don't
+    # want to change the code, so we have to extract it, then put it back.
+    dd if=${ROOT_DEV} bs=512 count=1 of=/tmp/oldpmbr.bin
+    echo "marking part $LEGACY_PART_NUM bootable (old)"
+    gpt -S boot -i $LEGACY_PART_NUM -b /tmp/oldpmbr.bin ${ROOT_DEV} 2>&1
+  fi
 
 fi
diff --git a/installer/chromeos-setimage b/installer/chromeos-setimage
--- a/installer/chromeos-setimage
+++ b/installer/chromeos-setimage
@@ -7,8 +7,12 @@
 
 # Load functions and constants for chromeos-install.
 . "$(dirname "$0")/chromeos-common.sh" || exit 1
-. /usr/lib/shflags || exit 1
-
+if [ -e /usr/lib/shflags ]; then
+  . /usr/lib/shflags || exit 1
+else
+  # Try to find it relative to src/scripts
+  . ../third_party/shflags/files/src/shflags || exit 1
+fi
 
 # The default device is the one we booted from.
 ROOTDEV=$(rootdev)
@@ -16,8 +20,20 @@ ROOTDEV=$(rootdev)
 DEFAULT_DST=$(get_block_dev_from_partition_dev ${ROOTDEV})
 
 DEFINE_string dst "${DEFAULT_DST}" "Boot device to update"
+# Any time the verified boot flags change, this is needed
+# as well as a new grub.cfg.
+DEFINE_string update_syslinux_cfg "" \
+  "If specified, the path to a syslinux root.[A|B].cfg."
+DEFINE_string update_grub_cfg "" \
+  "If specified, the path to a new grub.cfg."
+DEFINE_string update_vmlinuz "" \
+  "If specified, the path to a vmlinuz to use as syslinux's vmlinuz.[A|B]"
 DEFINE_boolean run_as_root ${FLAGS_FALSE} \
   "Allow root to run this script (Careful, it won't prompt for a password!)"
+DEFINE_boolean verified_boot ${FLAGS_FALSE} \
+  "Use a verified boot target. Default: false"
+DEFINE_string esp_mounted_at "" \
+  "Specify a location if the esp has already been mounted"
 
 # Parse command line
 FLAGS "$@" || exit 1
@@ -37,7 +53,6 @@ if [ -n "${@:-}" ]; then
   fi
 fi
 
-
 # Don't run this as root
 dont_run_as_root
 
@@ -49,24 +64,87 @@ then
 fi
 
 # Mount the EFI System Partition
-mountpoint=$(mktemp -d  /tmp/mountesp_XXXXXXXXX)
+if [ -n "$FLAGS_esp_mounted_at" ]; then
+  mountpoint="$FLAGS_esp_mounted_at"
+else
+  mountpoint=$(mktemp -d  /tmp/mountesp_XXXXXXXXX)
+  sudo mount $(make_partition_dev ${FLAGS_dst} 12) ${mountpoint}
+fi
 tempfile=$(mktemp /tmp/grubcfg_XXXXXXXXX)
-sudo mount ${FLAGS_dst}12 ${mountpoint}
+
+if [ -n "$FLAGS_update_syslinux_cfg" -a ! -r "$FLAGS_update_syslinux_cfg" ];
+then
+  echo "Specified syslinux root cfg file not found."
+  exit 1
+fi
 
 # Make the change
 if [ -n "${newimg:-}" ]; then
-  echo "Update boot default to menu item $newimg"
-  sed -e "s/^set default=.*/set default=${newimg}/" \
-    ${mountpoint}/efi/boot/grub.cfg > ${tempfile}
+  grubid=${newimg}
+  test ${FLAGS_verified_boot} -eq ${FLAGS_TRUE} && grubid=$((newimg+2))
+  if [ -z "$FLAGS_update_grub_cfg" ]; then
+    FLAGS_update_grub_cfg=${mountpoint}/efi/boot/grub.cfg
+  fi
+  echo "Update boot default to menu item $grubid"
+  sed -e "s/^set default=.*/set default=${grubid}/" \
+    $FLAGS_update_grub_cfg > ${tempfile}
   sudo cp ${tempfile} ${mountpoint}/efi/boot/grub.cfg
 fi
 
-echo "Current boot default is:"
+echo "Current EFI boot default is:"
 # Print the [new] default choice
 grep -qs '^set default=0' ${mountpoint}/efi/boot/grub.cfg && echo "A"
 grep -qs '^set default=1' ${mountpoint}/efi/boot/grub.cfg && echo "B"
+grep -qs '^set default=2' ${mountpoint}/efi/boot/grub.cfg && echo "A (verified)"
+grep -qs '^set default=3' ${mountpoint}/efi/boot/grub.cfg && echo "B (verified)"
+
+# Rinse and repeat for the Legacy BIOS bootloader (syslinux)
+if [ -n "${newimg:-}" ]; then
+  echo "Updating default syslinux target to $newimg"
+  target_hd=chromeos-hd
+  test ${FLAGS_verified_boot} -eq ${FLAGS_TRUE} && target_hd=chromeos-vhd
+
+  if [ ${newimg} -eq 0 ]; then
+    echo "DEFAULT ${target_hd}.A" > ${mountpoint}/syslinux/default.cfg
+    vmlinuz_tgt=${mountpoint}/syslinux/vmlinuz.A
+    syslinux_root_cfg=${mountpoint}/syslinux/root.A.cfg
+  fi
+
+  if [ ${newimg} -eq 1 ]; then
+    echo "DEFAULT ${target_hd}.B" > ${mountpoint}/syslinux/default.cfg
+    vmlinuz_tgt=${mountpoint}/syslinux/vmlinuz.B
+    syslinux_root_cfg=${mountpoint}/syslinux/root.B.cfg
+  fi
+
+  # Update the root.X.cfg in place if none given.
+  if [ -z "$FLAGS_update_syslinux_cfg" ]; then
+      FLAGS_update_syslinux_cfg=$syslinux_root_cfg
+  fi
+
+  # 3 and 5 are the current rootfs a and b partitions
+  DST_PART_A=$(make_partition_dev ${FLAGS_dst} 3)
+  DST_PART_B=$(make_partition_dev ${FLAGS_dst} 5)
+  sed -e "s|HDROOTA|${DST_PART_A}|g;s|HDROOTB|${DST_PART_B}|g" \
+    $FLAGS_update_syslinux_cfg > ${tempfile}
+  sudo cp ${tempfile} $syslinux_root_cfg
+
+  # We only need to do this for syslinux since grub can read the rootfs.
+  if [ -n "$FLAGS_update_vmlinuz" ]; then
+    echo "Updating vmlinuz..."
+    sudo cp -fL "$FLAGS_update_vmlinuz" "$vmlinuz_tgt"
+  fi
+fi
+
+echo "Current Legacy boot default is:"
+# Print the [new] default choice
+grep -qs 's-hd-A$' ${mountpoint}/syslinux/default.cfg && echo "A"
+grep -qs 's-hd-B$' ${mountpoint}/syslinux/default.cfg && echo "B"
+grep -qs 'vhd-A$' ${mountpoint}/syslinux/default.cfg && echo "A (verified)"
+grep -qs 'vhd-B$' ${mountpoint}/syslinux/default.cfg && echo "B (verified)"
 
 # Clean up
-sudo umount ${mountpoint}
 rm -f ${tempfile}
-rmdir ${mountpoint}
+if [ -z "$FLAGS_esp_mounted_at" ]; then
+  sudo umount ${mountpoint}
+  rmdir ${mountpoint}
+fi
