Turn ON firmware update on ARM in the postinst script.
There was a blocker in postinst to prevent firmware update for ARM.
This CL removes this blocker since we now have leave_firmware_alone and
force_update_frimware flags to control this behavior.

BUG=chromium-os:15247
TEST=run build_image to create an image; use tag_image.sh to remove the
leave_firmware_alone flag; use sign_official_build.sh to re-calculate the
root hash; run cros_image_to_target to update the image to the target device;
see the firmware updater runs and the new fimrware is updated.

Change-Id: I808f0fa77e267146770761d63de519a08ea46bcb
Reviewed-on: http://gerrit.chromium.org/gerrit/2368
Reviewed-by: Hung-Te Lin <hungte@chromium.org>
Tested-by: Tom Wai-Hong Tam <waihong@chromium.org>

diff --git a/installer/chromeos-chroot-postinst b/installer/chromeos-chroot-postinst
--- a/installer/chromeos-chroot-postinst
+++ b/installer/chromeos-chroot-postinst
@@ -337,20 +337,16 @@ rm -f /var/lib/ureadahead/*
 # See comments above about removing ureadahead files.
 touch /mnt/stateful_partition/.install_completed
 
-# TODO: support firmware update for ARM
-if [ ${IS_INTEL_ARCH} -eq 1 ]; then
-  update_firmware
-  FW_RC="$?"
-  if [ "$FW_RC" -ne 0 ]; then
-    # Note: This will only rollback the ChromeOS verified boot target.
-    # The assumption is that systems running firmware autoupdate
-    # are running H2C Bios. If the firmware updater crashes or writes
-    # corrupt data rather than gracefully failing, we'll probably need
-    # to recover with a recovery image.
-    echo "Firmware update failed."
-    echo "Rolling back update due to failure installing required firmware."
-    "$GPT" add -i $NEW_KERN_NUM -P 0 -S 0 -T 0 $ROOT_DEV
-    echo exit "$FW_RC" from postinst
-    exit "$FW_RC"
-  fi
+FW_RC=0
+update_firmware || FW_RC="$?"
+if [ "$FW_RC" -ne 0 ]; then
+  # Note: This will only rollback the ChromeOS verified boot target.
+  # The assumption is that systems running firmware autoupdate
+  # are not running legacy (non-ChromeOS) firmware. If the firmware
+  # updater crashes or writes corrupt data rather than gracefully
+  # failing, we'll probably need to recover with a recovery image.
+  echo "Firmware update failed (error code: $FW_RC)."
+  echo "Rolling back update due to failure installing required firmware."
+  "$GPT" add -i $NEW_KERN_NUM -P 0 -S 0 -T 0 $ROOT_DEV || true
+  exit "$FW_RC"
 fi
