update chromeos-install to support installing from an image file
Change-Id: I4ecefdd122c8df7bfe8d6cc89ac2f4c406c268a6

TEST=(1)tested on agz board with latest Cros FW using a factory_install image. Manually executed "chromeos-install" script to verify the existing functionality still behaves correctly; (2) repeat same test but using a non-dev recovery image and verified recovery behaves as expected with verified boot

Review URL: http://codereview.chromium.org/3051033

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -9,7 +9,8 @@
 . "$(dirname "$0")/chromeos-common.sh" || exit 1
 . /usr/lib/shflags || exit 1
 
-if [ $(uname -m) = "armv7l" ]; then
+MACHINE_NAME=$(uname -m)
+if [ "${MACHINE_NAME}" = "armv7l" ]; then
   DEFAULT_DST=/dev/mmcblk0
 else
   DEFAULT_DST=/dev/sda
@@ -30,6 +31,9 @@ DEFINE_boolean preserve_stateful ${FLAGS_FALSE} \
   "Don't create a new filesystem for the stateful partition. Be careful \
 using this option as this may make the stateful partition not mountable. \
 Default: False."
+DEFINE_string payload_image "" "Path to a Chromium OS image to install onto \
+the device's hard drive. Default: (empty)."
+
 
 # Parse command line
 FLAGS "$@" || exit 1
@@ -40,47 +44,62 @@ set -e
 # Don't run this as root
 dont_run_as_root
 
-# First find the root partition that we are installing from and verify it.
-ROOTDEV=$(rootdev)
+# Find root partition of the block device that we are installing from
+get_root_device() {
+  local root_dev=$(rootdev)
+  local on_dm=0
 
-# If we're on a verified rootfs, the rootdev won't be meaningful.
-ON_DM=0
-if echo "${ROOTDEV}" | grep -q '^/dev/mapper/'; then
-  ON_DM=1
-fi
-if [ "${ROOTDEV}" = "/dev/dm-0" ]; then
-  ON_DM=1
-fi
-if [ "${ON_DM}" -eq "1" ]; then
-  ROOTDEV="/dev/$(basename /sys/block/dm-0/slaves/*)"
-fi
+  # If we're on a verified rootfs, the rootdev won't be meaningful.
+  if echo "${root_dev}" | grep -q '^/dev/mapper/'; then
+    on_dm=1
+  fi
+  if [ "${root_dev}" = "/dev/dm-0" ]; then
+    on_dm=1
+  fi
+  if [ "${on_dm}" -eq "1" ]; then
+    root_dev="/dev/$(basename /sys/block/dm-0/slaves/*)"
+  fi
+  echo $root_dev
+}
 
-# From root partition to root block device.
-SRC=$(get_block_dev_from_partition_dev ${ROOTDEV})
-REMOVABLE=$(cat /sys/block/${SRC#/dev/}/removable)
-if [ "$FLAGS_skip_src_removable" -eq "${FLAGS_FALSE}" -a "$REMOVABLE" != "1" ]
-then
-  echo "Error: Source does not look like a removable device: $SRC"
-  exit 1
+# Check for optional payload image
+if [ -z "$FLAGS_payload_image" ]; then
+  # Find root partition of the root block device
+  SRC=$(get_block_dev_from_partition_dev $(get_root_device))
+
+  if [ "$FLAGS_skip_src_removable" -eq "${FLAGS_FALSE}" ]; then
+    if [ "$(cat /sys/block/${SRC#/dev/}/removable)" != "1" ]; then
+      echo "Error: Source does not look like a removable device: $SRC"
+      exit 1
+    fi
+  fi
+else
+  if [ -f "$FLAGS_payload_image" ]; then
+    # TODO(tgao): unpack partitions from image and verify
+    echo "TODO(tgao): unpack partitions from image and verify"
+  else
+    echo "Error: No payload image found at $FLAGS_payload_image"
+    exit 1
+  fi
 fi
 
 # Check out the dst device.
-if [ ! -b "$FLAGS_dst" ]
-then
+if [ ! -b "$FLAGS_dst" ]; then
   echo "Error: Unable to find destination block device: $FLAGS_dst"
   exit 1
 fi
-REMOVABLE=$(cat /sys/block/${FLAGS_dst#/dev/}/removable)
-if [ $? -ne 0 ]
-then
+
+DST_REMOVABLE=$(cat /sys/block/${FLAGS_dst#/dev/}/removable)
+if [ $? -ne 0 ]; then
   echo "Error: Invalid destination device (must be whole device): $FLAGS_dst"
   exit 1
 fi
-if [ "$REMOVABLE" != "0" ]
-then
+
+if [ "$DST_REMOVABLE" != "0" ]; then
   echo "Error: Attempt to install to a removeable device: $FLAGS_dst"
   exit 1
 fi
+
 if [ "$FLAGS_dst" = "$SRC" ]; then
   echo "Error: src and dst the same: $SRC = $FLAGS_dst"
   exit 1
@@ -94,7 +113,7 @@ sudo -K
 echo "This will erase all data at this destination: $FLAGS_dst"
 if [ "${FLAGS_yes}" -eq "$FLAGS_FALSE" ]; then
   read -p "Are you sure (y/N)? " SURE
-  if [ "$SURE" != "y" ] ; then
+  if [ "$SURE" != "y" ]; then
     echo "Ok, better safe than sorry; you answered '$SURE'."
     exit 1
   fi
@@ -159,13 +178,15 @@ my_cleanup() {
 ##############################################################################
 
 # What do we expect & require to have on the source device?
-STATEFUL_IMG=$(make_partition_dev ${SRC} 1)
-KERNEL_IMG=$(make_partition_dev ${SRC} 2)
-ROOTFS_IMG=$(make_partition_dev ${SRC} 3)
-OEM_IMG=$(make_partition_dev ${SRC} 8)
-ESP_IMG=$(make_partition_dev ${SRC} 12)
+if [ -z "$FLAGS_payload_image" ]; then
+  STATEFUL_IMG=$(make_partition_dev ${SRC} 1)
+  KERNEL_IMG=$(make_partition_dev ${SRC} 2)
+  ROOTFS_IMG=$(make_partition_dev ${SRC} 3)
+  OEM_IMG=$(make_partition_dev ${SRC} 8)
+  ESP_IMG=$(make_partition_dev ${SRC} 12)
+fi
 
-if [ $(uname -m) = "armv7l" ]; then
+if [ "$MACHINE_NAME" = "armv7l" ]; then
   PMBRCODE=/dev/zero
 else
   # Steal the PMBR code from the source MBR to put on the dest MBR, for booting
@@ -176,7 +197,7 @@ fi
 # Create the GPT.
 install_gpt $FLAGS_dst $ROOTFS_IMG $STATEFUL_IMG $PMBRCODE $ESP_IMG
 
-if [ $(uname -m) = "armv7l" ]; then
+if [ "$MACHINE_NAME" = "armv7l" ]; then
   DEVICE=$(echo $FLAGS_dst | sed -e 's/^.*\([0-9]\)$/\1/')
   MBR_SCRIPT_UIMG=$(make_arm_mbr ${START_KERN_A} ${NUM_KERN_SECTORS} ${DEVICE} "")
   sudo dd bs=1 count=`stat --printf="%s" ${MBR_SCRIPT_UIMG}` \
@@ -230,7 +251,7 @@ sudo dd if=${ESP_IMG} of=${FLAGS_dst} conv=notrunc bs=512 seek=${START_ESP}
 
 # TODO: support arm during postinst so that we get partition selection and
 #       verified boot.
-if [ $(uname -m) != "armv7l" ]; then
+if [ "$MACHINE_NAME" != "armv7l" ]; then
 
   # We can't guarantee that the kernel will see the new partition table, so
   # we can't use it directly. We could force the kernel to reload it with an
@@ -263,7 +284,7 @@ if [ $(uname -m) != "armv7l" ]; then
   trap - EXIT
 
   # Is there a better x86 test?
-  IS_INTEL_ARCH=$(uname -m | grep "^i.86\$" | wc -l)
+  IS_INTEL_ARCH=$(MACHINE_NAME | grep "^i.86\$" | wc -l)
   if [ "$IS_INTEL_ARCH" -eq "1" ]; then
     # Update EFI partition. This doesn't happen in /postinst b/c we use loop
     # device for mounting
@@ -310,7 +331,7 @@ fi
 # the release image, which could mask bugs.  Make sure every
 # item you add here is well justified.
 #
-if [ -f /root/.dev_mode ] ; then
+if [ -f /root/.dev_mode ]; then
   mount_on_loop_dev readwrite
   trap my_cleanup EXIT
   DIRLIST="
@@ -319,7 +340,7 @@ if [ -f /root/.dev_mode ] ; then
       dev_image
   "
   for DIR in ${DIRLIST}; do
-    if [ ! -d /mnt/stateful_partition/${DIR} ] ; then
+    if [ ! -d /mnt/stateful_partition/${DIR} ]; then
       continue
     fi
     PARENT=$(dirname ${DIR})
