Run hw diagnostics when we fail chromeos-install.
We run hw diagnostics and store them in /tmp. These hw diagnostics
give us the state of the disk. These can be passed to ninjas etc
if a device fails.

BUG=chromium:235068
TEST=Running install on a device -- check logs.

Change-Id: Ibcf80d4cc75d6947fb131879b011045fcf265532
Reviewed-on: https://gerrit.chromium.org/gerrit/49999
Reviewed-by: Chris Sosa <sosa@chromium.org>
Tested-by: Chris Sosa <sosa@chromium.org>
Commit-Queue: Chris Sosa <sosa@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -220,6 +220,8 @@ fi
 ##############################################################################
 # Helpful constants and functions.
 
+# Where to store any related hardware diagnostics data.
+HARDWARE_DIAGNOSTICS_PATH=/tmp/hardware_diagnostics.log
 PMBRCODE=/tmp/gptmbr.bin
 TMPFILE=/tmp/install-temp-file
 TMPMNT=/tmp/install-mount-point
@@ -323,6 +325,24 @@ check_non_empty_values() {
   return ${FLAGS_TRUE}
 }
 
+# Undo all mounts and loops and runs hw diagnostics on failure.
+cleanup_on_failure() {
+  set +e
+
+  # Generate the diagnostics log that can be used by a caller.
+  echo "Running a hw diagnostics test -- this will take a couple minutes."
+  badblocks -sv "$DST" 2>"${HARDWARE_DIAGNOSTICS_PATH}" 1>&2
+  cat "${HARDWARE_DIAGNOSTICS_PATH}"
+
+  # Run a few extra diagnostics and then them to stdout. These will be stored
+  # as part of the recovery.log for recovery images.
+  smartctl -l error "$DST"
+  smartctl -l selftest "$DST"
+  smartctl -a "$DST"
+
+  cleanup
+}
+
 # Undo all mounts and loops.
 cleanup() {
   set +e
@@ -343,7 +363,10 @@ cleanup() {
     rmdir "$ROOT"
   fi
 }
-trap cleanup EXIT
+
+# We untrap on success and run cleanup ourselves. Othewise, on any failure, run
+# our custom trap method to gather any diagnostic data before cleaning up.
+trap cleanup_on_failure EXIT
 
 ##############################################################################
 
@@ -552,6 +575,9 @@ loop_offset_cleanup
 
 # Force data to disk before we declare done.
 sync
+
+cleanup
+trap - EXIT
 
 echo "------------------------------------------------------------"
 echo ""
