chromeos-install: do not check dest removable when we have skipped it
We have a --skip_dst_removable flag that the code mostly supports, but
the initial variable setup is done outside of that check.  Move it in
the if statement since that is the only place that uses this variable.

BUG=chromium:236941
TEST=`chromeos-install --skip_dst_removable` no longer checks
TEST=`chromeos-install` still checks and works

Change-Id: I89c582d254f1163d9fd0eca24b66f40d9337f4a7
Reviewed-on: https://gerrit.chromium.org/gerrit/49955
Reviewed-by: Chris Sosa <sosa@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>

diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -179,18 +179,24 @@ if [ ! -b "$DST" ]; then
   exit 1
 fi
 
-DST_REMOVABLE=$(cat /sys/block/${DST#/dev/}/removable)
-if [ $? -ne 0 ]; then
-  echo "Error: Invalid destination device (must be whole device): $DST"
-  exit 1
-fi
+check_removable() {
+  if [ ${FLAGS_skip_dst_removable} -eq ${FLAGS_TRUE} ]; then
+    return
+  fi
 
-if [ "$FLAGS_skip_dst_removable" -eq "${FLAGS_FALSE}" ]; then
-  if [ "$DST_REMOVABLE" != "0" ]; then
+  local removable
+
+  if ! removable=$(cat /sys/block/${DST#/dev/}/removable); then
+    echo "Error: Invalid destination device (must be whole device): ${DST}"
+    exit 1
+  fi
+
+  if [ "${removable}" != "0" ]; then
     echo "Error: Attempt to install to a removeable device: $DST"
     exit 1
   fi
-fi
+}
+check_removable
 
 if [ "$DST" = "$SRC" ]; then
   echo "Error: src and dst the same: $SRC = $DST"
