Cleanup INSTALL_ROOT logic from postinstall scripts.
BUG=chromium-os:6803
TEST=ran AU with set -x and --debug

Change-Id: Icb79d0dc0ca4113192dfd1fa1e5ef97acdba5628

diff --git a/installer/chromeos-chroot-postinst b/installer/chromeos-chroot-postinst
--- a/installer/chromeos-chroot-postinst
+++ b/installer/chromeos-chroot-postinst
@@ -10,22 +10,18 @@
 # rootfs is mounted-read only and should not be updated.
 
 # Load helper functions
-INSTALL_ROOT=/
-. "${INSTALL_ROOT}"/usr/sbin/chromeos-common.sh || exit 1
-. "${INSTALL_ROOT}"/usr/lib/shflags || exit 1
+. /usr/sbin/chromeos-common.sh || exit 1
+. /usr/lib/shflags || exit 1
 
-# Process flags now, couldn't earlier since we needed INSTALL_ROOT to know where
-# to load shflags from.
 DEFINE_boolean debug ${FLAGS_FALSE} "Show debug output. Default: false"
 DEFINE_string esp_part_file "" "File containing the ESP partition"
-DEFINE_boolean postcommit ${FLAGS_FALSE} "Run postcommit"
 DEFINE_string src_version "0.0.0.0" "Current OS version"
 
 # WARNING: do NOT change this default value without consulting adlr/nsanders.
-# If you want to temporary enable firmware update for testing, create a
-# tag file in ${INSTALL_ROOT}/root/.force_update_firmware
+# If you want to temporary enable firmware update for testing, create a tag file
+# in /root/.force_update_firmware.
 FLAGS_firmware_default=${FLAGS_FALSE}
-if [ -f "${INSTALL_ROOT}/root/.force_update_firmware" ]; then
+if [ -f "/root/.force_update_firmware" ]; then
   FLAGS_firmware_default=${FLAGS_TRUE}
 fi
 DEFINE_boolean update_firmware $FLAGS_firmware_default "Enable firmware update."
@@ -103,7 +99,7 @@ if [ -n "$IS_UPDATE" ] &&
   version_less "${FLAGS_src_version}" 0.13.0.0 &&
   [ "${BOARD#x86-alex}" != "${BOARD}" ]; then
   echo "Force to re-generate VPD cached log file"
-  ${INSTALL_ROOT}/usr/sbin/dump_vpd_log --force || true
+  /usr/sbin/dump_vpd_log --force || true
 fi
 
 update_firmware() {
@@ -111,7 +107,7 @@ update_firmware() {
   # only after new kernel is actived (installed and made bootable),
   # otherwise new firmware with all old kernels may lead to recovery screen
   # (due to new key).
-  FIRMWARE_UPDATE_SCRIPT="${INSTALL_ROOT}/usr/sbin/chromeos-firmwareupdate"
+  FIRMWARE_UPDATE_SCRIPT="/usr/sbin/chromeos-firmwareupdate"
   if [ ${FLAGS_update_firmware} -eq "${FLAGS_TRUE}" -a \
        -x "${FIRMWARE_UPDATE_SCRIPT}" ]; then
     FIRMWARE_UPDATE_MODE=""
@@ -138,8 +134,7 @@ update_firmware() {
     fi
     FIRMWARE_UPDATE_ARGS=" $FIRMWARE_UPDATE_MODE "
     echo "Updating firmware ($FIRMWARE_UPDATE_ARGS)"
-    env INSTALL_ROOT="${INSTALL_ROOT}" \
-      "${FIRMWARE_UPDATE_SCRIPT}" ${FIRMWARE_UPDATE_ARGS}
+    env INSTALL_ROOT=/ "${FIRMWARE_UPDATE_SCRIPT}" ${FIRMWARE_UPDATE_ARGS}
     # Next step after postinst may take a lot of time (eg, disk wiping)
     # and people may confuse that as 'firmware update takes a long wait',
     # we explicitly prompt here.
@@ -193,217 +188,176 @@ update_firmware() {
   return 0  # success
 }
 
-if [ "${FLAGS_postcommit}" -eq "${FLAGS_FALSE}" ]; then
-  # Pre-commit. Returning an error here will prevent ever booting into the
-  # installed system.
+# Pre-commit. Returning an error here will prevent ever booting into the
+# installed system.
 
-  echo "Postinst running"
+echo "Postinst running"
 
-  # If this FS was mounted read-write, we can't do deltas from it. Mark the
-  # FS as such
-  (touch "${INSTALL_ROOT}/.nodelta" || true) > /dev/null 2>&1
+# If this FS was mounted read-write, we can't do deltas from it. Mark the
+# FS as such
+(touch "/.nodelta" || true) > /dev/null 2>&1
 
-  echo " Set boot target to ${INSTALL_DEV}:" \
-    "Partition ${NEW_PART_NUM}, Slot ${BOOT_SLOT}"
+echo " Set boot target to ${INSTALL_DEV}:" \
+  "Partition ${NEW_PART_NUM}, Slot ${BOOT_SLOT}"
 
-  # TODO(rkc): This is a bit of a hack - we're depending on the fact that our
-  # build machine will always be Intel based - if it isn't, VM builds will fail
-  # Install syslinux files on EFI partition
-  if [ -z "${IS_INSTALL}" -a "${IS_INTEL_ARCH}" -eq "1" ]; then
-    EFI_MNT=$(mktemp -d /tmp/EFI.XXXXXX)
-    if [ -z "${FLAGS_esp_part_file}" ]; then
-      EFI_PART=$(make_partition_dev "${ROOT_DEV}" "${LEGACY_PART_NUM}")
-    else
-      EFI_PART=$(losetup -f)
-      if [ -z "${EFI_PART}" ]; then
-        # It's okay to die here; this parameter will never be given on live
-        # system - this is only in case of mounted image postinst runs
-        die "No free loop device. Free up a loop device or reboot. Exiting."
-      fi
-      losetup "${EFI_PART}" "${FLAGS_esp_part_file}"
+# TODO(rkc): This is a bit of a hack - we're depending on the fact that our
+# build machine will always be Intel based - if it isn't, VM builds will fail
+# Install syslinux files on EFI partition
+if [ -z "${IS_INSTALL}" -a "${IS_INTEL_ARCH}" -eq "1" ]; then
+  EFI_MNT=$(mktemp -d /tmp/EFI.XXXXXX)
+  if [ -z "${FLAGS_esp_part_file}" ]; then
+    EFI_PART=$(make_partition_dev "${ROOT_DEV}" "${LEGACY_PART_NUM}")
+  else
+    EFI_PART=$(losetup -f)
+    if [ -z "${EFI_PART}" ]; then
+      # It's okay to die here; this parameter will never be given on live
+      # system - this is only in case of mounted image postinst runs
+      die "No free loop device. Free up a loop device or reboot. Exiting."
     fi
-    # TODO: scary hack to work around disk corruption
-    # Note, we mean to run fsck.vfat twice, fsck.vfat returns status 1 for
-    # "Recoverable errors have been detected or dosfsck has discovered an
-    # internal inconsistency."  If the first fsck fixes errors the first time,
-    # the second fsck will succeed.  Otherwise, nuke it from orbit.
-    if ! "${INSTALL_ROOT}/sbin/fsck.vfat" -a "${EFI_PART}"; then
-      if ! "${INSTALL_ROOT}/sbin/fsck.vfat" -a "${EFI_PART}"; then
-        echo "Rebuilding FAT filessytem."
-        "${INSTALL_ROOT}/usr/sbin/mkfs.vfat" "${EFI_PART}"
-      fi
-    fi
-    mount "${EFI_PART}" "${EFI_MNT}"
-    set +e
-    # Copy over the templates, but don't clobber anything.
-    # Clobbering is boot_slot specific and handled by setimage below.
-    cp -nR "${INSTALL_ROOT}"/boot/syslinux "${EFI_MNT}"
-    ERR=${?}
-    echo "Updating syslinux"
-    # Update all legacy bootloaders.
-    if [ "${ERR}" -eq "0" ]; then
-      syslinux_cfg="${INSTALL_ROOT}/boot/syslinux/root.${BOOT_SLOT}.cfg"
-      grub_cfg="${INSTALL_ROOT}/boot/efi/boot/grub.cfg"
-      ROOT_DEV_PARAM=""
-      if [ -n "$IS_UPDATE" ]; then
-        ROOT_DEV_PARAM="--rootfs_image=$INSTALL_DEV --kernel_image=$NEW_K_DEV"
-      fi
-      "${INSTALL_ROOT}"/usr/sbin/chromeos-setimage ${BOOT_SLOT} \
-          --dst=${ROOT_DEV} --run_as_root \
-          --install_root="${INSTALL_ROOT}" \
-          --update_syslinux_cfg="${syslinux_cfg}" \
-          --update_grub_cfg="${grub_cfg}" \
-          --esp_mounted_at="${EFI_MNT}" \
-          --update_vmlinuz=${INSTALL_ROOT}/boot/vmlinuz \
-          ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
-      ERR=${?}
-    fi
-    umount "${EFI_MNT}"
-    rmdir "${EFI_MNT}"
-    if [ "${ERR}" -ne "0" ]; then
-      echo "Failed to copy syslinux files in and make them bootable."
-      exit 1
-    fi
-    /usr/bin/syslinux "${EFI_PART}"
-    ERR=${?}
-    if (expr match "${EFI_PART}" "/dev/loop*" >/dev/null); then
-      losetup -d "${EFI_PART}"
-    fi
-    set -e
-    if [ "${ERR}" -ne "0" ]; then
-      echo "Failed to run syslinux on: ${EFI_PART}"
-      exit 1
+    losetup "${EFI_PART}" "${FLAGS_esp_part_file}"
+  fi
+  # TODO: scary hack to work around disk corruption
+  # Note, we mean to run fsck.vfat twice, fsck.vfat returns status 1 for
+  # "Recoverable errors have been detected or dosfsck has discovered an
+  # internal inconsistency."  If the first fsck fixes errors the first time,
+  # the second fsck will succeed.  Otherwise, nuke it from orbit.
+  if ! "/sbin/fsck.vfat" -a "${EFI_PART}"; then
+    if ! "/sbin/fsck.vfat" -a "${EFI_PART}"; then
+      echo "Rebuilding FAT filessytem."
+      "/usr/sbin/mkfs.vfat" "${EFI_PART}"
     fi
   fi
-
-  # This export is so that locate_gpt will look within this install
-  # partition to find that copy of the cgpt program.
-  # Note, this only works when running $INSTALL_ROOT/postinst.
-  export DEFAULT_CHROOT_DIR="${INSTALL_ROOT}"
-  locate_gpt  # sets $GPT to cgpt executable (or fails and exits immediately)
-
-  # If we're working on a real machine, not a mounted image, only then
-  # run the gpt tool to manipulate the partitions - if we're touching
-  # the ESP from a file, it means we are not on the target hardware, making
-  # the GPT and firmware scripts inapplicable nor are we auto-updating
-  if [ -z "${FLAGS_esp_part_file}" ]; then
-    echo "Updating the root filesystem hashes and legacy bootloaders"
+  mount "${EFI_PART}" "${EFI_MNT}"
+  set +e
+  # Copy over the templates, but don't clobber anything.
+  # Clobbering is boot_slot specific and handled by setimage below.
+  cp -nR /boot/syslinux "${EFI_MNT}"
+  ERR=${?}
+  echo "Updating syslinux"
+  # Update all legacy bootloaders.
+  if [ "${ERR}" -eq "0" ]; then
+    syslinux_cfg="/boot/syslinux/root.${BOOT_SLOT}.cfg"
+    grub_cfg="/boot/efi/boot/grub.cfg"
     ROOT_DEV_PARAM=""
     if [ -n "$IS_UPDATE" ]; then
       ROOT_DEV_PARAM="--rootfs_image=$INSTALL_DEV --kernel_image=$NEW_K_DEV"
     fi
-    if [ ${IS_INTEL_ARCH} -eq 1 ]; then
-      # Ensure we use a template from the INSTALL_ROOT for both grub
-      # and syslinux otherwise we can never update them with new rootfs
-      # vboot configuration data.
-      syslinux_cfg="${INSTALL_ROOT}/boot/syslinux/root.${BOOT_SLOT}.cfg"
-      grub_cfg="${INSTALL_ROOT}/boot/efi/boot/grub.cfg"
-      "${INSTALL_ROOT}"/usr/sbin/chromeos-setimage ${BOOT_SLOT} \
-          --dst=${ROOT_DEV} --run_as_root \
-          --install_root="${INSTALL_ROOT}" \
-          --update_syslinux_cfg="${syslinux_cfg}" \
-          --update_grub_cfg="${grub_cfg}" \
-          --update_vmlinuz=${INSTALL_ROOT}/boot/vmlinuz \
-          ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
-    else
-      "${INSTALL_ROOT}"/usr/sbin/chromeos-setimage ${BOOT_SLOT} \
-          --dst=${ROOT_DEV} --run_as_root \
-          --install_root="${INSTALL_ROOT}" \
-          ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
-    fi
-
-    echo "Updating Partition Table Attributes..."
-    NEW_KERN_NUM=$(( $NEW_PART_NUM - 1))
-    # Make updated partition highest priority for next reboot
-    "$GPT" prioritize -i $NEW_KERN_NUM $ROOT_DEV
-    # Set kernel as successful=1 except when autoupdating
-    new_as_successful=0
-    if [ -n "${IS_FACTORY_INSTALL}" -o \
-         -n "${IS_RECOVERY_INSTALL}" -o \
-         -n "${IS_INSTALL}" ]; then
-      new_as_successful=1
-    fi
-    "$GPT" add -i $NEW_KERN_NUM -S $new_as_successful -T 6 $ROOT_DEV
-
-    # Set up gpt boot selection for legacy devices.
-    # flush linux caches; seems to be necessary
-    sync
-    echo 3 > /proc/sys/vm/drop_caches
-
-    echo "Updating gpt PMBR target for legacy BIOS"
-    # Configure the PMBR to boot the new image.
-    echo "marking part $LEGACY_PART_NUM bootable (new)"
-    "$GPT" boot -i $LEGACY_PART_NUM ${ROOT_DEV} 2>&1
-
-    if [ ${MAKE_DEV_READONLY} -eq ${FLAGS_TRUE} ]; then
-      echo "Making dev ${INSTALL_DEV} read-only"
-      hdparm -r 1 "${INSTALL_DEV}"
-    fi
-
-    # At this point in the script, the new partition has been marked bootable
-    # and a reboot will boot into it. Thus, it's important that any future
-    # errors in this script do not cause this script to return failure unless
-    # in factory mode.
-    if [ -z "${IS_FACTORY_INSTALL}" ]; then
-      set +e
-    fi
-
-    # We have a new image, making the ureadahead pack files
-    # out-of-date.  Delete the files so that ureadahead will
-    # regenerate them on the next reboot.
-    # WARNING: This doesn't work with upgrade from USB, rather than full
-    # install/recovery. We don't have support for it as it'll increase the
-    # complexity here, and only developers do upgrade from USB.
-    rm -f /var/lib/ureadahead/*
-
-    # Create a file indicating that the install is completed. The file
-    # will be used in /sbin/chromeos_startup to run tasks on the next boot.
-    # See comments above about removing ureadahead files.
-    touch /mnt/stateful_partition/.install_completed
-
-    # TODO: support firmware update for ARM
-    if [ ${IS_INTEL_ARCH} -eq 1 ] && ! update_firmware; then
-      # Note: This will only rollback the ChromeOS verified boot target.
-      # The assumption is that systems running firmware autoupdate
-      # are running H2C Bios. If the firmware updater crashes or writes
-      # corrupt data rather than gracefully failing, we'll probably need
-      # to recover with a recovery image.
-      echo "Firmware update failed."
-      echo "Rolling back update due to failure installing required firmware."
-      "$GPT" add -i $NEW_KERN_NUM -P 0 -S 0 -T 0 $ROOT_DEV
-      exit 1
-    fi
+    /usr/sbin/chromeos-setimage ${BOOT_SLOT} \
+        --dst=${ROOT_DEV} --run_as_root \
+        --update_syslinux_cfg="${syslinux_cfg}" \
+        --update_grub_cfg="${grub_cfg}" \
+        --esp_mounted_at="${EFI_MNT}" \
+        --update_vmlinuz=/boot/vmlinuz \
+        ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
+    ERR=${?}
   fi
-else
-  # Post-commit. At this point an unexpected reboot may boot the installed
-  # system, but returning an error here will cause the updater to try to
-  # not boot the installed system, instead keeping the existing system.
-  echo -n  # this is a noop, required for 'sh'
+  umount "${EFI_MNT}"
+  rmdir "${EFI_MNT}"
+  if [ "${ERR}" -ne "0" ]; then
+    echo "Failed to copy syslinux files in and make them bootable."
+    exit 1
+  fi
+  /usr/bin/syslinux "${EFI_PART}"
+  ERR=${?}
+  if (expr match "${EFI_PART}" "/dev/loop*" >/dev/null); then
+    losetup -d "${EFI_PART}"
+  fi
+  set -e
+  if [ "${ERR}" -ne "0" ]; then
+    echo "Failed to run syslinux on: ${EFI_PART}"
+    exit 1
+  fi
+fi
 
-  # We are deprecating post-commit postinst, so do not put anything in here.
+# This export is so that locate_gpt will look within this install partition to
+# find that copy of the cgpt program.
+export DEFAULT_CHROOT_DIR=/
+locate_gpt  # sets $GPT to cgpt executable (or fails and exits immediately)
 
-  echo "Updating gpt PMBR target for legacy BIOS (post-commit)"
-  # I know we aren't supposed to put anything here, but here is the
-  # justification:
-  # The updater in 0.7.42.* sets the rootfs bootable after postinst (precommit)
-  # is run, and then runs postinst (postcommit). Later versions of the updater
-  # neither mark partitions bootable, nor run postinst (postcommit). In those
-  # newer versions, this code won't be run, but it won't need to be run.
-  # If we didn't care about clients as old as 0.7.42.*, we could leave this
-  # area empty. Unfortunately, we can't update old updaters.
-
-  # At some point, when we don't care about clients that old (0.7.42.*),
-  # We should remove this whole code path in this file.
-
-
-  if [ -x "${INSTALL_ROOT}"/usr/bin/cgpt ]; then
-    echo "marking part $LEGACY_PART_NUM bootable (new)"
-    "${INSTALL_ROOT}"/usr/bin/cgpt boot -i $LEGACY_PART_NUM ${ROOT_DEV} 2>&1
+# If we're working on a real machine, not a mounted image, only then
+# run the gpt tool to manipulate the partitions - if we're touching
+# the ESP from a file, it means we are not on the target hardware, making
+# the GPT and firmware scripts inapplicable nor are we auto-updating
+if [ -z "${FLAGS_esp_part_file}" ]; then
+  echo "Updating the root filesystem hashes and legacy bootloaders"
+  ROOT_DEV_PARAM=""
+  if [ -n "$IS_UPDATE" ]; then
+    ROOT_DEV_PARAM="--rootfs_image=$INSTALL_DEV --kernel_image=$NEW_K_DEV"
+  fi
+  if [ ${IS_INTEL_ARCH} -eq 1 ]; then
+    syslinux_cfg="/boot/syslinux/root.${BOOT_SLOT}.cfg"
+    grub_cfg="/boot/efi/boot/grub.cfg"
+    /usr/sbin/chromeos-setimage ${BOOT_SLOT} \
+        --dst=${ROOT_DEV} --run_as_root \
+        --update_syslinux_cfg="${syslinux_cfg}" \
+        --update_grub_cfg="${grub_cfg}" \
+        --update_vmlinuz=/boot/vmlinuz \
+        ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
   else
-    # The old gpt tool requires a -b arg to specify the PMBR bootcode. We don't
-    # want to change the code, so we have to extract it, then put it back.
-    dd if=${ROOT_DEV} bs=512 count=1 of=/tmp/oldpmbr.bin
-    echo "marking part $LEGACY_PART_NUM bootable (old)"
-    gpt -S boot -i $LEGACY_PART_NUM -b /tmp/oldpmbr.bin ${ROOT_DEV} 2>&1
+    /usr/sbin/chromeos-setimage ${BOOT_SLOT} \
+        --dst=${ROOT_DEV} --run_as_root \
+        ${SUB_CMD_DEBUG_FLAG} ${ROOT_DEV_PARAM}
+  fi
+
+  echo "Updating Partition Table Attributes..."
+  NEW_KERN_NUM=$(( $NEW_PART_NUM - 1))
+  # Make updated partition highest priority for next reboot
+  "$GPT" prioritize -i $NEW_KERN_NUM $ROOT_DEV
+  # Set kernel as successful=1 except when autoupdating
+  new_as_successful=0
+  if [ -n "${IS_FACTORY_INSTALL}" -o \
+       -n "${IS_RECOVERY_INSTALL}" -o \
+       -n "${IS_INSTALL}" ]; then
+    new_as_successful=1
+  fi
+  "$GPT" add -i $NEW_KERN_NUM -S $new_as_successful -T 6 $ROOT_DEV
+
+  # Set up gpt boot selection for legacy devices.
+  # flush linux caches; seems to be necessary
+  sync
+  echo 3 > /proc/sys/vm/drop_caches
+
+  echo "Updating gpt PMBR target for legacy BIOS"
+  # Configure the PMBR to boot the new image.
+  echo "marking part $LEGACY_PART_NUM bootable (new)"
+  "$GPT" boot -i $LEGACY_PART_NUM ${ROOT_DEV} 2>&1
+
+  if [ ${MAKE_DEV_READONLY} -eq ${FLAGS_TRUE} ]; then
+    echo "Making dev ${INSTALL_DEV} read-only"
+    hdparm -r 1 "${INSTALL_DEV}"
+  fi
+
+  # At this point in the script, the new partition has been marked bootable
+  # and a reboot will boot into it. Thus, it's important that any future
+  # errors in this script do not cause this script to return failure unless
+  # in factory mode.
+  if [ -z "${IS_FACTORY_INSTALL}" ]; then
+    set +e
+  fi
+
+  # We have a new image, making the ureadahead pack files
+  # out-of-date.  Delete the files so that ureadahead will
+  # regenerate them on the next reboot.
+  # WARNING: This doesn't work with upgrade from USB, rather than full
+  # install/recovery. We don't have support for it as it'll increase the
+  # complexity here, and only developers do upgrade from USB.
+  rm -f /var/lib/ureadahead/*
+
+  # Create a file indicating that the install is completed. The file
+  # will be used in /sbin/chromeos_startup to run tasks on the next boot.
+  # See comments above about removing ureadahead files.
+  touch /mnt/stateful_partition/.install_completed
+
+  # TODO: support firmware update for ARM
+  if [ ${IS_INTEL_ARCH} -eq 1 ] && ! update_firmware; then
+    # Note: This will only rollback the ChromeOS verified boot target.
+    # The assumption is that systems running firmware autoupdate
+    # are running H2C Bios. If the firmware updater crashes or writes
+    # corrupt data rather than gracefully failing, we'll probably need
+    # to recover with a recovery image.
+    echo "Firmware update failed."
+    echo "Rolling back update due to failure installing required firmware."
+    "$GPT" add -i $NEW_KERN_NUM -P 0 -S 0 -T 0 $ROOT_DEV
+    exit 1
   fi
 fi
